### ISSUE TITLE
Pls fix that Some chapter content of documents missing the pictures

### ISSUE THREAD

**Issue by svcg** [tal-tech/go-zero#1004]
URL: https://go-zero.dev/cn/service-deployment.html
Chapter: 2.2、 添加全局变量
Content: 如图
![WechatIMG33](https://user-images.githubusercontent.com/32574915/132272989-62af83b5-56ad-4c2b-b263-9cc9656a3604.jpeg)

When you fixed ， tell me  with email.

**Comment by anqiansong** [comment]
bug提错地方了，应该属于[go-zero-doc](https://github.com/zeromicro/go-zero-doc)项目，不过已经解决了
