### ISSUE TITLE
gozero logx.Disable()关闭logx,如何使用中间件 recover 捕获http panic

### ISSUE THREAD

**Issue by ltinyho** [tal-tech/go-zero#1019]
gozero logx.Disable()关闭logx,如何使用中间件 recover 捕获http panic呢?
中间件里面是固定的,加自己的log middleware在最后面捕获不到 panic

**Comment by kevwan** [comment]
show me the code. :)

**Comment by ltinyho** [comment]
表述有问题哈,panic是能recover,但是gozero logx.Disable()后日志不能打印出来.想用自己写的日志中间件打印出recover记录.
现在不能自定义中间件,想问下这种应该怎么处理?
![image](https://user-images.githubusercontent.com/28479270/132950653-c61a375c-f0de-4dd3-9611-0c89ce1af493.png)

**Comment by kevwan** [comment]
这种情况你可以自己加一个RecoverHandler中间件来捕获并记录异常

**Comment by ltinyho** [comment]
已经被内部的RecoverHandler了捕获了,应该不能再自己加RecoverHandler了吧

**Comment by kevwan** [comment]
> 已经被内部的RecoverHandler了捕获了,应该不能再自己加RecoverHandler了吧

不是应该，你写代码试一下就知道了的

代码见：https://github.com/kevwan/zero-issues/tree/main/1019

**Comment by ltinyho** [comment]
感谢,确实偷懒了,代码的问题跑一下就能出结果
