### ISSUE TITLE
怎么接入监控系统

### ISSUE THREAD

**Issue by leafmirror** [tal-tech/go-zero#1020]

**Comment by kevwan** [comment]
现在我们是直接打到ELK里查看的，v1.2.1会接入opentelemetry.

**Comment by Rebellioncry** [comment]
@leafmirror 请问最新版对接opentelemetry了吗？如何对接？ELK对接又是怎么做的，有没有相关配置和教程？

**Comment by kevwan** [comment]
opentelemetry已经接入，ELK，我们有go-stash可以替代logstash，前面用filebeat收集。

**Comment by Rebellioncry** [comment]
@kevwan 开源的吗？有没有文档？

**Comment by kevwan** [comment]
https://github.com/kevwan/go-stash

**Comment by Rebellioncry** [comment]
这些对接在开发文档里找不到，希望补全或给个教程
