### ISSUE TITLE
httpx.Parse(r, &req) json 校验必填,空字符串未校验

### ISSUE THREAD

**Issue by ltinyho** [tal-tech/go-zero#1021]
```
name   string `json:"name"`                          // 名字
```
json 校验 name字段必须有,但是可以为空字符串.
如何校验空字符串

**Comment by kevwan** [comment]
这是go的常见问题，如果实在需要，可以用 `*string`

**Comment by ltinyho** [comment]
了解了,看文档以为是支持校验空字符串的.
![image](https://user-images.githubusercontent.com/28479270/132950189-9f5ced83-7329-4862-aad4-f5b6727845e3.png)
是不是需要修改一下文档呢?

**Comment by kevwan** [comment]
改成必填？把不可为空去掉，对吧？

**Comment by ltinyho** [comment]
嗯嗯,主要是想说明不会校验空字符
