### ISSUE TITLE
[error ] :   goctl  installed from disk for goland plugins

### ISSUE THREAD

**Issue by achilsh** [tal-tech/go-zero#1038]
1. local env:  mac 
2. install goctl from local disk:       goland--> preferences ---> plugins ---> install plugin  from disks

problem:
   Fail to load plugin descriptor from file go-zero-1.2.0.zip

**Comment by achilsh** [comment]
yes...i download go-zero  from github of go-zero release.

**Comment by achilsh** [comment]
![image](https://user-images.githubusercontent.com/6417640/133096344-484ec381-059a-4992-87de-11e2429ae646.png)

**Comment by kevwan** [comment]
It's not for goland. It's just a source code package of go-zero itself.

**Comment by achilsh** [comment]
yes, i seach goctl in plugin market,  it's ok. 
but install in local zip file, it's not ok for goland.

**Comment by kevwan** [comment]
> yes, i seach goctl in plugin market, it's ok.
> but install in local zip file, it's not ok for goland.

zip file is not for goland.

**Comment by achilsh** [comment]
ok, i see. just install goctl from plugin market...
