### ISSUE TITLE
Windows下使用goctl会输出异常信息

### ISSUE THREAD

**Issue by alexcdever** [tal-tech/go-zero#105]
系统信息：
![image](https://user-images.githubusercontent.com/14200813/94505611-0e88b400-023e-11eb-82c9-972bf539bc3d.png)
go版本：
![image](https://user-images.githubusercontent.com/14200813/94505737-57d90380-023e-11eb-8e1a-5618a1b74e76.png)
异常信息：
![image](https://user-images.githubusercontent.com/14200813/94505568-f0bb4f00-023d-11eb-8461-93b666b99007.png)

这种情况我在家里的macOS试了，执行`goctl api new test`是没有问题的，但公司配的是Windows，在公司电脑上会出现这种异常信息，所以我的想法就是系统平台的原因，另外Windows下执行这边命令后，生成的目录也是不全的，如图：
![image](https://user-images.githubusercontent.com/14200813/94506130-40e6e100-023f-11eb-8ebe-9cf8ae03129a.png)

**Comment by miaogaolin** [comment]
你先试着在powershell里执行试试，看65001可能和编码有关系

**Comment by kevwan** [comment]
不能重现，如果依然有问题，你再reopen

**Comment by alexcdever** [comment]
不好意思，这两天工作有点忙，回复慢。
我用Windows自带的powershell的话还是这样
![image](https://user-images.githubusercontent.com/14200813/94637327-d6e73e00-0309-11eb-9a33-3d6f659632e4.png)




> 你先试着在powershell里执行试试，看65001可能和编码有关系

这个65001是我在改了Windows的默认编码为UTF-8后出现的



> 不能重现，如果依然有问题，你再reopen

嗯嗯，我后天回到家后就在家里试试，看看这个问题是不是我公司这台电脑才会出现的个例

**Comment by kevwan** [comment]
好的，给出详细的环境和步骤哈

**Comment by alexcdever** [comment]
这个假期真的是一波多折，昨晚终于在一个虚拟的Windows10上装上了go-zero和goctl，在那个虚拟机里goctl确实是能正常使用的，所以这个问题应该就是我公司电脑上才会发生的个例了
