### ISSUE TITLE
.api文件是否可以支持include语法

### ISSUE THREAD

**Issue by voidint** [tal-tech/go-zero#124]
- 一旦接口数量变多，将不同接口定义到不同的.api文件中进行归类就变得自然而然了。在一个入口的.api文件中include多个.api文件，goctl执行时只需要指定一个入口的.api文件。
- 当然，这是一个锦上添花的功能，目前的方式依然可以正常使用。

**Comment by kevwan** [comment]
这个暂时不会支持哈，保持最简🤝

**Comment by xkeyi** [comment]
现在是所有的api只能写在一个.api文件里面么？
