### ISSUE TITLE
执行go run check.go -f etc/check.yaml报如下错误

### ISSUE THREAD

**Issue by laoliang330** [tal-tech/go-zero#127]
# go run check.go -f etc/check.yaml
Starting rpc server at 127.0.0.1:8080...
{"level":"warn","ts":"2020-10-14T15:29:28.833+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection closed"}
{"@timestamp":"2020-10-14T15:29:28.834+08","level":"error","content":"server.go:83 context deadline exceeded"}
panic: context deadline exceeded

goroutine 1 [running]:
github.com/tal-tech/go-zero/zrpc.(*RpcServer).Start(0xc0001249a0)
        /root/go/pkg/mod/github.com/tal-tech/go-zero@v1.0.20/zrpc/server.go:84 +0xce
main.main()
        /root/golang/bookstore/rpc/check/check.go:37 +0x33f
exit status 2

**Comment by kevwan** [comment]
etcd, rpc服务没起

**Comment by laoliang330** [comment]
谢谢。搞定了。
能选择其他的服务发现框架吗？

**Comment by kevwan** [comment]
> 谢谢。搞定了。
> 能选择其他的服务发现框架吗？

不能

**Comment by gocpplua** [comment]
> etcd, rpc服务没起

我按照文档启动了etcd的，不过还是遇到这个问题。 我的操作如下：
大家在看快速开发章节中的"微服务"， 其中在启动服务并验证模块中"启动user rpc"，我执行:
go run user.go -f etc/user.yaml, 显示rpc启动，但是一会儿出现下述错误：

{"level":"warn","ts":"2022-03-21T12:03:38.206+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004001c0/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection closed before server preface received"}
{"@timestamp":"2022-03-21T12:03:38.206+08:00","level":"error","content":"server.go:90 context deadline exceeded"}
panic: context deadline exceeded

goroutine 1 [running]:
github.com/zeromicro/go-zero/zrpc.(*RpcServer).Start(0x1ad1500)
        /home/XXX/chenqi1/go/pkg/mod/github.com/zeromicro/go-zero@v1.3.1/zrpc/server.go:91 +0x88
main.main()
        /data/coding/study-go-zero/mall/go-zero-demo/mall/user/rpc/user.go:39 +0x2c5
exit status 2

**Comment by kevwan** [comment]
Start the rpc service first, or add `NonBlock: true` in yaml file.

**Comment by gocpplua** [comment]
> 

我在etc/user.yaml下面添加了 NonBlock: true (尝试和Name同级，也尝试在Etcd下)，还是报错：
{"level":"warn","ts":"2022-03-21T13:25:35.276+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003e01c0/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
{"@timestamp":"2022-03-21T13:25:35.276+08:00","level":"error","content":"server.go:90 context deadline exceeded"}
panic: context deadline exceeded

**Comment by gocpplua** [comment]
> > 
> 
> 我在etc/user.yaml下面添加了 NonBlock: true (尝试和Name同级，也尝试在Etcd下)，还是报错： {"level":"warn","ts":"2022-03-21T13:25:35.276+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003e01c0/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused""} {"@timestamp":"2022-03-21T13:25:35.276+08:00","level":"error","content":"server.go:90 context deadline exceeded"} panic: context deadline exceeded

因为我使用的etcd版本是2.2.5，升级到3.5.2就没有存在这个问题了
