### ISSUE TITLE
请问能开源一个复杂一点的完整的项目源码么？

### ISSUE THREAD

**Issue by xkeyi** [tal-tech/go-zero#138]
麻雀虽小，五脏俱全的那种，一个简单的博客网站就行。

**Comment by kevwan** [comment]
bookstore就是一个完整示例

**Comment by kevwan** [comment]
> 麻雀虽小，五脏俱全的那种，一个简单的博客网站就行。

你看了bookstore示例嘛？

**Comment by jackluo2012** [comment]
哈哈哈，同问 +1

**Comment by kevwan** [comment]
我们内外同源，内部有完整的实践

社区你可以问问，不少人已经在生产上用了go-zero

**Comment by pengdaCN** [comment]
请问那个bookstore的github链接是多少呀
