### ISSUE TITLE
Question about the circuit breaker

### ISSUE THREAD

**Issue by supermario1990** [tal-tech/go-zero#141]
why not use [hystrix-go](https://github.com/afex/hystrix-go) but implementing one yourself. Could you please talk about some  comparisons between `core/breaker` and `hystrix-go`. I'm curious about the new design, thx.

**Comment by kevwan** [comment]
the circuit breaker in go-zero is google sre algorithm, which is better than hystrix algorithm. sre one has better time to recover (TTR) than hystrix one. there is no open/close state for sre algorithm.

please search for the details in google.
