### ISSUE TITLE
api与rpc需要单独实现业务逻辑部分吗？

### ISSUE THREAD

**Issue by cqlucasho** [tal-tech/go-zero#150]

**Comment by kevwan** [comment]
rpc是主要业务逻辑承载部分，api是聚合层

**Comment by cqlucasho** [comment]
感觉api部分重了，api应该直接基于logic生成到子模块一起，不应该再生成一个单独的子模块的结构，我看半天蒙的，还有建议提个建议，能不能改下文件命令，对于一个有代码洁癖强迫症的人，受不了单词之间没有分割，哈哈哈。

**Comment by cqlucasho** [comment]
> rpc是主要业务逻辑承载部分，api是聚合层

感觉api部分重了，api应该直接基于logic生成到子模块一起，不应该再生成一个单独的子模块的结构，我看半天蒙的，还有建议提个建议，能不能改下文件命令，对于一个有代码洁癖强迫症的人，受不了单词之间没有分割，哈哈哈。

**Comment by kevwan** [comment]
> > rpc是主要业务逻辑承载部分，api是聚合层
> 
> 感觉api部分重了，api应该直接基于logic生成到子模块一起，不应该再生成一个单独的子模块的结构，我看半天蒙的，还有提个建议，能不能改下文件命名，对于一个有代码洁癖强迫症的人，受不了单词之间没有分割，哈哈哈。

『api应该直接基于logic生成到子模块一起』这个啥意思？贴个图说下？

『受不了单词之间没有分割』这个要改所有文件名才行

**Comment by cqlucasho** [comment]
> > > rpc是主要业务逻辑承载部分，api是聚合层
> > 
> > 
> > 感觉api部分重了，api应该直接基于logic生成到子模块一起，不应该再生成一个单独的子模块的结构，我看半天蒙的，还有提个建议，能不能改下文件命名，对于一个有代码洁癖强迫症的人，受不了单词之间没有分割，哈哈哈。
> 
> 『api应该直接基于logic生成到子模块一起』这个啥意思？贴个图说下？
> 
> 『受不了单词之间没有分割』这个要改所有文件名才行

比如user服务模块的业务逻辑部分已经实现, 那么对于api我可以直接通过goctl对user的业务方法(public)生成对外api, 放置在internal的内部, 如果某个api接口需要整合其它接口可以再根据自身业务手动调整.

**Comment by kevwan** [comment]
> > > > rpc是主要业务逻辑承载部分，api是聚合层
> > > 
> > > 
> > > 感觉api部分重了，api应该直接基于logic生成到子模块一起，不应该再生成一个单独的子模块的结构，我看半天蒙的，还有提个建议，能不能改下文件命名，对于一个有代码洁癖强迫症的人，受不了单词之间没有分割，哈哈哈。
> > 
> > 
> > 『api应该直接基于logic生成到子模块一起』这个啥意思？贴个图说下？
> > 『受不了单词之间没有分割』这个要改所有文件名才行
> 
> 比如user服务模块的业务逻辑部分已经实现, 那么对于api我可以直接通过goctl对user的业务方法(public)生成对外api, 放置在internal的内部, 如果某个api接口需要整合其它接口可以再根据自身业务手动调整.
> 
> 如果我user服务都不开启，那对应的api其实也不应该开放出去才对，以我现在的理解啊（不知道是否完全正确，不对请不介意）
> 
> 1. 如果我user服务关闭后是否还需要再去把对应的api也去关掉？
> 2. 有这种情况，我一个对外api下，可能还包含其它服务的调用，所以肯定是不能关的，那用户调用的已关闭服务接口的时候，不是就走不通了，多了一些无用的请求, 虽然有fail fast机制，但是感觉还是让用户走了一些没必要的流程.

api gateway是聚合层，你未必每个都对应rpc，如果要停掉rpc，那么你可以把api gateway里面的路由也去掉的
