### ISSUE TITLE
redis pool是否应该支持可配置？

### ISSUE THREAD

**Issue by lwhcv** [tal-tech/go-zero#164]
目前看了下core/store/redis里面redis连接的代码，redis pool参数都是默认的，满足不了所有公司的需求，比如redis的最大连接数、redis的最大空闲数以及超时时间等，这样会更灵活一些？

**Comment by kevwan** [comment]
有实际场景再reopen哈

**Comment by pabno** [comment]
> 

这种场景应该很常见，不知道能否支持一下。对于第三方开源库的封装，如果配置项不完全暴露出来，那开源库的能力将会大打折扣

**Comment by pabno** [comment]
> > 
> 
> 这种场景应该很常见，不知道能否支持一下。对于第三方开源库的封装，如果配置项不完全暴露出来，那开源库的能力将会大打折扣

@kevwan
