### ISSUE TITLE
go 微服务的数据库选型，多数据库事务问题

### ISSUE THREAD

**Issue by flew990** [tal-tech/go-zero#17]
我在参考贵司该项目时有几个问题困扰？
①：请问贵司出于什么考虑将之前的Mongo换成mysql了呢？（我司重度mongo用户😂）
②：Mongo不可以做微服务的存储仓吗？
③：该项目的分布式事务时啥方案啊？

劳烦解惑啊

**Comment by kevwan** [comment]
1，我们把关系型数据放到mysql，文档型数据依然放在mongodb
2，mongodb也是可以用的，看选择吧，你们数据规模有多大？
3，go-zero里不包含分布式事务框架

🤝

**Comment by flew990** [comment]
目前我司mongo有20多G数据量，所有业务都是mongo存。
现在需求是往微服务走，但分布式事务没闹明白？go里有分布式事务这种轮子推荐吗？ 

谢谢 kevwan

**Comment by kevwan** [comment]
core/stores/sqlx包里也有Transact方法，但是你要在分布式下用的话，得自己控制分布式的commit/rollback.

我之前做分布式事务也是自己写的

**Comment by flew990** [comment]
@kevwan 👌 感谢解惑！
