### ISSUE TITLE
依赖问题：undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4

### ISSUE THREAD

**Issue by XiangYu0777** [tal-tech/go-zero#185]
系统环境：

平台：MacOS Catalina 10.15.5
GO ENV:
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xx/Library/Caches/go-build"
GOENV="/Users/xx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/xx/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn/,direct"
GOROOT="/usr/local/Cellar/go/1.15.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/xx/docker-files/dnmp/www/shorturl/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q1/k1fjfgbs1ynbrzj33jqqg7680000gp/T/go-build909429352=/tmp/go-build -gno-record-gcc-switches -fno-common"

Go 依赖做了调整：
```
replace (
	github.com/golang/protobuf => github.com/golang/protobuf v1.3.2
	google.golang.org/grpc => google.golang.org/grpc v1.26.0
)
```
其他依赖保持默认的状态

运行教程 “快速构建高并发微服务”
执行 ```go run transform.go -f etc/transform.yaml```
出现以下错误：

```
# google.golang.org/genproto/googleapis/rpc/status
/Users/xx/go/pkg/mod/google.golang.org/genproto@v0.0.0-20200729003335-053ba62fc06f/googleapis/rpc/status/status.pb.go:42:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
# google.golang.org/genproto/googleapis/api/annotations
/Users/xx/go/pkg/mod/google.golang.org/genproto@v0.0.0-20200729003335-053ba62fc06f/googleapis/api/annotations/annotations.pb.go:41:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
/Users/xx/go/pkg/mod/google.golang.org/genproto@v0.0.0-20200729003335-053ba62fc06f/googleapis/api/annotations/client.pb.go:41:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
/Users/xx/go/pkg/mod/google.golang.org/genproto@v0.0.0-20200729003335-053ba62fc06f/googleapis/api/annotations/field_behavior.pb.go:42:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
/Users/xx/go/pkg/mod/google.golang.org/genproto@v0.0.0-20200729003335-053ba62fc06f/googleapis/api/annotations/http.pb.go:41:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4
/Users/xx/go/pkg/mod/google.golang.org/genproto@v0.0.0-20200729003335-053ba62fc06f/googleapis/api/annotations/resource.pb.go:42:11: undefined: "github.com/golang/protobuf/proto".ProtoPackageIsVersion4

```

**疑问🤔️**：网上查了以下，说是 ```github.com/golang/protobuf v1.3.2``` 依赖的版本太低了，但是就是因为之前是 1.4.1 导致有问题才做了降级，现在这个问题该怎么处理呢，不可能再做升级处理吧

**Comment by kevwan** [comment]
`github.com/golang/protobuf => github.com/golang/protobuf v1.3.2`
这一行去掉试试
