### ISSUE TITLE
goctl api文件 import

### ISSUE THREAD

**Issue by edieruby** [tal-tech/go-zero#188]
https://www.yuque.com/tal-tech/go-zero/ze9i30
    import "foo1.api"
    import "foo2.api"
应该是没有引号的.

另外goland插件上 对import支持的也是带引号的. 没引号就会提示错误, 
命令行运行没问题.

应该是带引号的 goctl里可能没把引号去掉
#190

**Comment by kevwan** [comment]
already supported.
