### ISSUE TITLE
protoc-gen-go 版本问题

### ISSUE THREAD

**Issue by yujintang** [tal-tech/go-zero#214]
goctl rpc proto -src transform.proto -dir .

当编译pb文件时候，会出现两个报错
1. Missing 'go_package' option in "transform.proto"

2. --go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC

**Comment by yujintang** [comment]
在当前项目下安装，使用旧版  go get github.com/golang/protobuf/protoc-gen-go@v1.4.0

**Comment by RoshanDev** [comment]
已经 2021 年 4 月了，还没更新呀。emm

**Comment by RoshanDev** [comment]
附上通用问题[解决方案](https://github.com/tal-tech/go-zero/issues/576#issuecomment-804716550)，注意超链接链接的后面的逗号。
