### ISSUE TITLE
etcd grpc

### ISSUE THREAD

**Issue by l0n3rs** [tal-tech/go-zero#235]
按照文档一步一步走的，直接生成会爆这个，手动proto生成也爆这个，etcd启动了的。

M:\Gostudy\zero\rpc>goctl rpc new server
protoc  -I=M:\Gostudy\zero\rpc\server server.proto --go_out=plugins=grpc:M:\Gostudy\zero\rpc\server\server
Done.

M:\Gostudy\zero\rpc>ls
server

M:\Gostudy\zero\rpc>cd server

M:\Gostudy\zero\rpc\server>ls
default.etcd  etc  go.mod  internal  server  server.go  server.proto  serverclient

M:\Gostudy\zero\rpc\server>go run server.go
go: finding module for package github.com/tal-tech/go-zero/zrpc
go: finding module for package github.com/tal-tech/go-zero/core/conf
go: finding module for package google.golang.org/grpc/status
go: finding module for package github.com/tal-tech/go-zero/core/logx
go: finding module for package google.golang.org/grpc/codes
go: finding module for package github.com/golang/protobuf/proto
go: finding module for package google.golang.org/grpc
go: found github.com/tal-tech/go-zero/core/conf in github.com/tal-tech/go-zero v1.0.29
go: found github.com/tal-tech/go-zero/zrpc in github.com/tal-tech/go-zero v1.0.29
go: found google.golang.org/grpc in google.golang.org/grpc v1.33.2
go: found github.com/golang/protobuf/proto in github.com/golang/protobuf v1.4.3
go: found google.golang.org/grpc/codes in google.golang.org/grpc v1.33.2
go: found google.golang.org/grpc/status in google.golang.org/grpc v1.33.2
go: found github.com/tal-tech/go-zero/core/logx in github.com/tal-tech/go-zero v1.0.29
# go.etcd.io/etcd/clientv3/balancer/picker
M:\GOPATH\pkg\mod\go.etcd.io\etcd@v0.0.0-20200402134248-51bdeb39e698\clientv3\balancer\picker\err.go:25:9: cannot use &errPicker literal (type *errPicker) as type Picker in return argument:
        *errPicker does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
M:\GOPATH\pkg\mod\go.etcd.io\etcd@v0.0.0-20200402134248-51bdeb39e698\clientv3\balancer\picker\roundrobin_balanced.go:33:9: cannot use &rrBalanced literal (type *rrBalanced) as type Picker in return argument:
        *rrBalanced does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
# github.com/tal-tech/go-zero/zrpc/internal/balancer/p2c
M:\GOPATH\pkg\mod\github.com\tal-tech\go-zero@v1.0.29\zrpc\internal\balancer\p2c\p2c.go:41:32: not enough arguments in call to base.NewBalancerBuilder
        have (string, *p2cPickerBuilder)
        want (string, base.PickerBuilder, base.Config)
M:\GOPATH\pkg\mod\github.com\tal-tech\go-zero@v1.0.29\zrpc\internal\balancer\p2c\p2c.go:58:9: cannot use &p2cPicker literal (type *p2cPicker) as type balancer.Picker in return argument:
        *p2cPicker does not implement balancer.Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)

M:\Gostudy\zero\rpc\server>

**Comment by kevwan** [comment]
使用grpc 1.29.1
