### ISSUE TITLE
如何API 参数自动校验

### ISSUE THREAD

**Issue by alulu-zh** [tal-tech/go-zero#239]
如何做API 参数自动校验，是否可以像gin中使用的validator一样，利用tag来自动做参数校验？

**Comment by kevwan** [comment]
https://github.com/tal-tech/zero-doc/blob/main/doc/mapping.md

**Comment by itsukirt** [comment]
Hi, I read the documentation and it helped me a lot, but it seems that the automatic parameter validation is not powerful enough, do I have any other options? Thanks for your hard work!

**Comment by kevwan** [comment]
> Hi, I read the documentation and it helped me a lot, but it seems that the automatic parameter validation is not powerful enough, do I have any other options? Thanks for your hard work!

You can use third party validator together with go-zero.

**Comment by carr0t2** [comment]
> https://go-zero.dev/cn/api-grammar.html

没看到任何一个文档页面提到api参数校验,比如json,validate,optional等关键字的使用方法
