### ISSUE TITLE
wsl下cgroups环境问题导致goctl无法运行

### ISSUE THREAD

**Issue by funlake** [tal-tech/go-zero#24]
➜  go-zero goctl api -o greet.api
2020/08/27 10:59:46 cpu_linux.go:27 open cpuacct.usage_percpu: no such file or directory
2020/08/27 10:59:46 {"@timestamp":"2020-08-27T10:59:46.111+08","level":"fatal","content":"cpu_linux.go:27 open cpuacct.usage_percpu: no such file or directory"}

这块cpu相关的stat是否可以通过配置屏蔽？

**Comment by kevwan** [comment]
fixed, 多谢反馈！
