### ISSUE TITLE
能否完善一下支持特性，校验

### ISSUE THREAD

**Issue by yuhai-yang** [tal-tech/go-zero#245]
丰富一下文档
![image](https://user-images.githubusercontent.com/52445959/101236034-968cad80-3708-11eb-87f2-8bb8c372b38e.png)

**Comment by kevwan** [comment]
https://github.com/tal-tech/zero-doc/blob/main/doc/mapping.md#12-%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C%E4%BB%A5%E7%94%A8%E6%88%B7userapi%E6%96%87%E4%BB%B6%E4%B8%BA%E4%BE%8B

看看这个文档是不是你想要的
