### ISSUE TITLE
关于整套框架案例的线上发布流程有参考吗？

### ISSUE THREAD

**Issue by xiaopenggithub** [tal-tech/go-zero#246]
发现框架很强悍，示例代码已经能在本地环境运行，现在遇到的问题想请教：

1 本地开发中，每个服务都已能单独运行，线上环境需要如何部署（我们目前用的是阿里云）
2 如何部署扩缩容

（有文档参考也行）

**Comment by kevwan** [comment]
`goctl docker` 命令可以生成Dockerfile
近期会增加
`goctl kube` 命令生成k8s部署文件

**Comment by kevwan** [comment]
> `goctl docker` 命令可以生成Dockerfile
> 
> 近期会增加
> 
> `goctl kube` 命令生成k8s部署文件

已支持
