### ISSUE TITLE
在ARM 芯片的mac book上编译，会有报错

### ISSUE THREAD

**Issue by zhuyaguang** [tal-tech/go-zero#248]
assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1021334d8 abi_kind=6 emulation_interval=[0x1021712f4,0x102171308) instruction_interval=[0x1021712e0, 0x102171308) x86_rip=0x101c9d9
(ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)

![image](https://user-images.githubusercontent.com/8857976/101301038-87c20a00-3872-11eb-8e97-f9c47e9f0e71.png)

**Comment by kevwan** [comment]
M1吗？

**Comment by zhuyaguang** [comment]
> M1吗？

是的

**Comment by kevwan** [comment]
> > M1吗？
> 
> 是的

这个只能等官方修复吧

**Comment by shaolei** [comment]
> > M1吗？
> 
> 是的

golang1.16才支持这个芯片，现在的版本不支持

**Comment by defp** [comment]
go version go1.16beta1 darwin/arm64 可以了

![image](https://user-images.githubusercontent.com/612381/103968068-358c4580-519e-11eb-9ed9-2a6038a5fe01.png)

**Comment by LoveScotty** [comment]
大佬问下这个完全修复了嘛，怎么我的还是有问题咧

**Comment by kevwan** [comment]
> 大佬问下这个完全修复了嘛，怎么我的还是有问题咧

go 1.16解决了，我们解决不了呢

**Comment by LoveScotty** [comment]
go1.16beta1版可以，但是go1.16却有问题...
