### ISSUE TITLE
goctl生成的文件不容易和其他.go文件区分开来，建议换一种易区分的命名方式

### ISSUE THREAD

**Issue by Altruiste1** [tal-tech/go-zero#262]
在go-zero的example里注意到一些文件是通过goctl生成的，在文件首行有注释// Code generated by goctl. DO NOT EDIT.
但是有一个问题，生成的.go文件命名风格和我们通常的命名风格类似，这样在阅读的时候不容易区分哪些是goctl生成的，哪些是自己手动添加的，可以参考proto生成的.go文件，后缀为.proto.go这样的多段式命名，区分goctl生成的文件和手动添加的文件
例如：type.go=====>type.zero.go 

https://github.com/tal-tech/go-zero/blob/master/example/bookstore/api/internal/types/types.go
![image](https://user-images.githubusercontent.com/50795154/101589799-1f1a8f00-3a24-11eb-856c-ea3e77a0e568.png)

**Comment by bernadit** [comment]
DO NOT EDIT 

人家生成的代码里都这样写了的

**Comment by Altruiste1** [comment]
@bernadit DO NOT EDIT，我描述第一行提到了这个我知道有这个注释，但是文件代码超过一个屏幕后，你能保证你每次看文件都会先看第一行吗

**Comment by golyu** [comment]
如果你用的是goland,你去修改文件内容,最上面就会有警告提示,如果你平时编码规范,注意警告,这个很明显了
