### ISSUE TITLE
goctl 与 文件名规范

### ISSUE THREAD

**Issue by stu2162583** [tal-tech/go-zero#264]
不知道是不是我没找到解决方案。

servicecontext.go，感觉最起码的规范应该有一些，ServiceContext.go 或者 service_context.go

而handler，每个router 都是新建一个handler，不允许多个handler在一个handler文件中（不知道是否是必须的强制规范）

而且生成的handler名称也是userloginhandler.go 或者 userregisterhandler.go, 虽然很可能不需要再进行更改，但是文件名称的命名也是一个工程中比较重要的一部分。

尝试 \@handler user_register_ 不允许携带 _

**Comment by kevwan** [comment]
`-style` 参数可以试下

api文件里可以用 `group`  指令控制handler分到不同包下

**Comment by stu2162583** [comment]
> `-style` 参数可以试下
> 
> api文件里可以用 `group` 指令控制handler分到不同包下

感谢k大，按照您说的，已经在文档中找到了解决方案，但是我建议默认或者在文档一开始就提出这个 style 的参数会比较好一些。
记录一下：
// 文件命名的问题，两种格式
goctl api go -style="go_zero" -api bookstore.api -dir .
goctl api go -style="GoZero" -api gobug.api -dir .

// 分组的问题，生成的handler都在 greet 文件夹下
@server(
    group: greet
)
service user-api {
    @handler ping
    get /user/ping

    @handler login
    post /user/login (LoginReq) returns (LoginReply)

    @handler updateUser
    post /user/info/update (UserInfoUpdateReq)

    @handler userInfo
    get /user/info returns (UserInfoReply)
}
