### ISSUE TITLE
有没有更详尽的教程啊

### ISSUE THREAD

**Issue by bernadit** [tal-tech/go-zero#273]
比如怎么手工调用  redis 集群, mysql 集群

自从限流这些, 日志, 好多模块，你只是在 readme 上写，很难找到在哪里用 的... 

而且有的教程，和实际的不一样，写代码当中要自己摸索才能搞对 , 估计是代码更新，但是教程并没有及时更新的原因

这个框架确实不错, 希望作者坚持下去

就是教程太少了 ,找教程太难, 很担心作者, 哪天不维护了,有问题找不到地方解决...

**Comment by kevwan** [comment]
你可以在代码里 `find references` 就可以找到使用的地方，而且都是有单测覆盖的

**Comment by kevwan** [comment]
[https://zero.gocn.vip](https://zero.gocn.vip/)

**Comment by niezuxue** [comment]
可能是我水平有限，反正看文档感觉不是连续的 有断层，然后只能找找别的地方是怎么用的。。

**Comment by kevwan** [comment]
> 因为自己水平有限，看文档感觉不是连续的 有断层，然后只能找找别的地方是怎么用的。。 也是建议文档更为详细

先跟着示例走一遍哈，有问题群里交流
