### ISSUE TITLE
Congratulations and questions

### ISSUE THREAD

**Issue by frederikhors** [tal-tech/go-zero#280]
Amazing work! Awesome, really!

Two questions:

1. why isn't it on awesome-go yet (https://github.com/avelino/awesome-go)?

1. Can I generate GraphQL?

**Comment by kevwan** [comment]
Thank you!

1. I didn't submit go-zero to awecome-go, will do it later. Thanks for pointing out.
2. Did you mean generate GraphQL from .api file?

**Comment by kevwan** [comment]
> Amazing work! Awesome, really!
> 
> Two questions:
> 
> 1. why isn't it on awesome-go yet (https://github.com/avelino/awesome-go)?
> 2. Can I generate GraphQL?

The awesome-go PR.
https://github.com/avelino/awesome-go/pull/3397

**Comment by frederikhors** [comment]
> Did you mean generate GraphQL from .api file?

Yeah. I would like to generate GraphQL API with your tool. Is it possible?

**Comment by kevwan** [comment]
Sorry, not supported yet.

`goctl` support plugins. Maybe you can write a GraghQL plugin to do that.

**Comment by gaohuag** [comment]
> Sorry, not supported yet.
> 
> `goctl` support plugins. Maybe you can write a GraghQL plugin to do that.

It's great
