### ISSUE TITLE
PeroidLimit和TokenLimit用法请教

### ISSUE THREAD

**Issue by zltgo** [tal-tech/go-zero#288]
-  1）问一下PeroidLimit和TokenLimit为和接口设计的不一样？

         PeroidLimit有Take(key string)接口，可以在运行时指定key，

        而TokenLimit是在初始化时指定key,运行时只有Allow()接口。
   
        如果要用TokenLimit对每个用户调用某接口进行限流，目前是不是无法实现?
        是因为这两种limit的使用场景不同么？

-  2）框架很好，功能很强大，希望能用起来。

        目前官方文档比较零散，官方示例book等已学习。示例只涵盖的最基础的功能，
        如何基于go-zero开发实际项目，还没有完整概念，也不太清楚应该如何整合go-zero提供的各类工具。

        作者能否考虑出一个功能较完整的最佳实践案例，或者推荐一个依赖go-zero的线上项目，方便学习研究。

感谢！

**Comment by kevwan** [comment]
不好意思，回复晚了
这个是应用场景的区别哈
PeroidLimit是为了比如多长时间内每个用户只能做几次某一个动作，这种是为了大量key的场景设计的
TokenLimit是为了比如给某个业务限流，这种一般是对一个key做频率限制用的

两者场景不同决定了接口不同，这样用起来最方便哈
