### ISSUE TITLE
RefreshCpu中计算usage的原理

### ISSUE THREAD

**Issue by superblacker** [tal-tech/go-zero#290]

**Comment by superblacker** [comment]
主要是 systemDelta * quota 不理解

**Comment by kevwan** [comment]
> 主要是systemDelta*quota, 以及对cpu = cpuᵗ⁻¹ * beta + cpuᵗ * (1 - beta) 这条公式不理解

这个是滑动平均的算法，比如如果 beta 取 0.9，那么相当于前10条的平均值

**Comment by superblacker** [comment]
cpuᵗ⁻¹并没有做初始化, 一开始为0. 计算出来的cpuᵗ 好像不是想要的值?

**Comment by kevwan** [comment]
> cpuᵗ⁻¹并没有做初始化, 一开始为0. 计算出来的cpuᵗ 好像不是想要的值?

这个by design，没有关系的，因为只有cpu超过某个值才会触发动作。
