### ISSUE TITLE
http 请求参数解析报错

### ISSUE THREAD

**Issue by hydrogenwuyan** [tal-tech/go-zero#291]
请求中带有数组，如：GET /book/add?name=a&name=b&name=c，解析报错。
看了下源码，解析参数时使用了如下函数：
```go
type Values map[string][]string

// Get gets the first value associated with the given key.
// If there are no values associated with the key, Get returns
// the empty string. To access multiple values, use the map
// directly.
func (v Values) Get(key string) string {
	if v == nil {
		return ""
	}
	vs := v[key]
	if len(vs) == 0 {
		return ""
	}
	return vs[0]
}
```
 请问之后会解决这个问题吗？如果解决的话会在多久之后的版本呢？

**Comment by kevwan** [comment]
这个是Go的吧，我解决不了呢

而且你这个用户不规范哈

**Comment by liuhuiping2013** [comment]
https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string

@kevwan 
这里讨论各语言的 web 框架对 form 中数组的支持，nodejs 是比较不错的，可以参考一下
![图片](https://user-images.githubusercontent.com/10127284/127091145-2d12b3d0-5c8e-4a62-9680-68577b214fa4.png)

**Comment by niezuxue** [comment]
在requests.go文件的ParseForm方法，下面的处理感觉应该不能饿用r.Form.Get()来取值，因为get只取一个元素。
`params := make(map[string]interface{}, len(r.Form))
	for name := range r.Form {
		formValue := r.Form.Get(name)
		if len(formValue) > 0 {
			params[name] = formValue
		}
	}`

**Comment by asmoker** [comment]
https://github.com/zeromicro/go-zero/issues/2334

**Comment by shyandsy** [comment]
框架层面如果能支持逗号分割的数组解析，就很方便

我自己写的解析，支持type_ids=1,2,3,4 这种格式
