### ISSUE TITLE
rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by caseylai** [tal-tech/go-zero#292]
对shorturl示例程序进行wrk压力测试中发现，只要连接数较大（-c连接数大于-t线程数的10倍以上，如-t10 -c100）时，gRPC服务大概率就会出现不稳定的情况，开始出现错误，如下（在两台独立的电脑上部署测试，可以复现）：

{"@timestamp":"2020-12-15T15:09:57.967+08","level":"info","duration":"250.8ms","content":"fail - discov:/localhost:2379/transform.rpc/transform.transformer/expand - shorten:\"8415a8\" - rpc error: code = Canceled desc = context canceled","trace":"1380b2aefad30c00","span":"0.1"}

同时日志会记录503失败：

{"@timestamp":"2020-12-15T15:09:57.974+08","level":"error","content":"loghandler.go:135 503 - /expand?shorten=8415a8 - [::1]:50281 -  - 257.6ms\nGET /expand?shorten=8415a8 HTTP/1.1\r\nHost: localhost:8888\r\n\r\n","trace":"1380b2aefad30c00","span":"0"}

经过代码调试，此报错由grpc框架接收端抛出，是在等待接收数据包时，context被关闭，导致请求被cancel的情况，但没有跟踪到context被关闭的具体原因。试过设置gRPC的Timeout，但没有作用。

另外，目前在Mac Pro（CPU 2.6GHz 六核 i7，OS 版本 10.15.7）上 wrk -t10 -c80 能跑出最高的QPS是1万左右，和示例程序的Benchmark 3万相差甚远，不知道是否还需要额外做和设置。

所用的Go版本是1.15.6，依赖包是
	github.com/tal-tech/go-zero v1.0.29 （默认的1.0.16版本也有此问题）
	google.golang.org/grpc v1.29.1
	google.golang.org/protobuf v1.25.0 （默认的github.com/golang/protobuf v1.4.2也有此问题）

**Comment by caseylai** [comment]
又多测试了几次，Update：

以上测试在Goland中进行（Goland的Run、Debug、以及Terminal中均可复现），但在Mac自带的Terminal下正常未出现报错。
QPS的问题应该是受日志输出的影响，将日志的Level设为error后，QPS可达到3万以上，是打开日志的3倍以上。

**Comment by a775189488** [comment]
我测试rpc接口也有楼主的报错情况。测试接口为自己写的测试接口，测试数量大概是2000并发。但是我这边的情况是在client发送rpc请求的时候就已经报错code = Canceled desc = context canceled了。并没有发送到服务端

**Comment by a775189488** [comment]
> 我测试rpc接口也有楼主的报错情况。测试接口为自己写的测试接口，测试数量大概是2000并发。但是我这边的情况是在client发送rpc请求的时候就已经报错code = Canceled desc = context canceled了。并没有发送到服务端

客户端的关键代码如下：
`
	client, err := zrpc.NewClient(zrpc.RpcClientConf{
		Endpoints: []string{rpcAddr},
		Timeout: 5000,
	})
	if err != nil {
		fmt.Printf("Connect to rpc server %s fail, err: %v, use time: %v \n", *targetIp, err, time.Now().Sub(preDial))
		return
	}
`

**Comment by kevwan** [comment]
能否给个完整操作步骤？可以用hey代替wrk试试

**Comment by kevwan** [comment]
duplicate of #294

**Comment by kzhan** [comment]
此问题有后续吗?

**Comment by kzhan** [comment]
> > 我测试rpc接口也有楼主的报错情况。测试接口为自己写的测试接口，测试数量大概是2000并发。但是我这边的情况是在client发送rpc请求的时候就已经报错code = Canceled desc = context canceled了。并没有发送到服务端
> 
> 客户端的关键代码如下：
> 
> ```
> 	client, err := zrpc.NewClient(zrpc.RpcClientConf{
> 		Endpoints: []string{rpcAddr},
> 		Timeout: 5000,
> 	})
> 	if err != nil {
> 		fmt.Printf("Connect to rpc server %s fail, err: %v, use time: %v \n", *targetIp, err, time.Now().Sub(preDial))
> 		return
> 	}
> ```

现在问题解决了吗?我目前也遇到此问题

**Comment by kevwan** [comment]
wrk的问题

**Comment by tanqili** [comment]
我遇到这个问题了，有两种情况会出现这个问题：
1、客户端调用的context关闭了
2、服务端调用提前返回，也会导致这个问题
你这个问题如果客户端调用的context没关，那么肯定是服务端写的有问题，没有接收完客户端的流数据，就提前返回导致的。希望对所有遇到这个问题的人有帮助

**Comment by kzhan** [comment]
> 对shorturl示例程序进行wrk压力测试中发现，只要连接数较大（-c连接数大于-t线程数的10倍以上，如-t10 -c100）时，gRPC服务大概率就会出现不稳定的情况，开始出现错误，如下（在两台独立的电脑上部署测试，可以复现）：
> 
> {"@timestamp":"2020-12-15T15:09:57.967+08","level":"info","duration":"250.8ms","content":"fail - discov:/localhost:2379/transform.rpc/transform.transformer/expand - shorten:"8415a8" - rpc error: code = Canceled desc = context canceled","trace":"1380b2aefad30c00","span":"0.1"}
> 
> 同时日志会记录503失败：
> 
> {"@timestamp":"2020-12-15T15:09:57.974+08","level":"error","content":"loghandler.go:135 503 - /expand?shorten=8415a8 - [::1]:50281 - - 257.6ms\nGET /expand?shorten=8415a8 HTTP/1.1\r\nHost: localhost:8888\r\n\r\n","trace":"1380b2aefad30c00","span":"0"}
> 
> 经过代码调试，此报错由grpc框架接收端抛出，是在等待接收数据包时，context被关闭，导致请求被cancel的情况，但没有跟踪到context被关闭的具体原因。试过设置gRPC的Timeout，但没有作用。
> 
> 另外，目前在Mac Pro（CPU 2.6GHz 六核 i7，OS 版本 10.15.7）上 wrk -t10 -c80 能跑出最高的QPS是1万左右，和示例程序的Benchmark 3万相差甚远，不知道是否还需要额外做和设置。
> 
> 所用的Go版本是1.15.6，依赖包是
> github.com/tal-tech/go-zero v1.0.29 （默认的1.0.16版本也有此问题）
> google.golang.org/grpc v1.29.1
> google.golang.org/protobuf v1.25.0 （默认的github.com/golang/protobuf v1.4.2也有此问题）


老哥,这个问题有结局解决吗?

**Comment by kzhan** [comment]
> wrk的问题

wrk 压测客户端 取消了?

**Comment by kevwan** [comment]
> > wrk的问题
> 
> wrk 压测客户端 取消了?

对的
