### ISSUE TITLE
go 1.14下安装goctl后无法正常执行

### ISSUE THREAD

**Issue by y00rb** [tal-tech/go-zero#298]
环境： go 1.14, module和proxy都已经打开
无论执行`GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/go-zero/tools/goctl`还是`go get -u github.com/tal-tech/go-zero/tools/goctl` 都没有显示人和网warning或者error。
安装后无法运行goctl，
`zsh: command not found: goctl`
删掉了$GOPATH下的`./pkg/mod/github/tal-tech/go-zero`再执行也是一样的问题。

**Comment by kevwan** [comment]
你需要把 goctl 所在目录加入到 $PATH 里哈

**Comment by y00rb** [comment]
文档不是说，运行上面的安装命令，会安装`goctl`到$GOPATH/bin吗？
<img width="812" alt="image" src="https://user-images.githubusercontent.com/444876/102567148-dc3f7200-411b-11eb-94d9-117d89f25e35.png">

**Comment by kevwan** [comment]
> 文档不是说，运行上面的安装命令，会安装`goctl`到$GOPATH/bin吗？
> <img alt="image" width="812" src="https://user-images.githubusercontent.com/444876/102567148-dc3f7200-411b-11eb-94d9-117d89f25e35.png">

那么你的$GOPATH/bin在$PATH里面？

**Comment by y00rb** [comment]
我的.zshrc 的一个配置
[image:DA70CB4E-209C-4225-AF0E-D616756DE82B-292-0000072891CFC27E/E0E296C8-4AF2-4868-BA17-AA9B17F5BE27.png]
然后我的$GOPATH/bin并没有`goctl`
[image:AA2023F9-8468-4DCC-97C6-4558F7572A04-292-0000072D8CF05C94/55428C97-0810-422D-8A42-9C6F4B10782D.png]

**Comment by kevwan** [comment]
这个你google下哈，这是go使用问题呢

**Comment by y00rb** [comment]
哪方面的问题能指明一下吗？goplo, goimports, godef, dlv 这些安装了后都是可以正常使用。是哪里配置有问题吗？

**Comment by y00rb** [comment]
解决了，是GOBIN的路径之前做实验被修改成别的了。可能就导致了这个问题
