### ISSUE TITLE
win10下遇到的两个bug

### ISSUE THREAD

**Issue by xhochipe** [tal-tech/go-zero#30]
1:goctl工具的bug，拉去的最新源码编译的
   
![image](https://user-images.githubusercontent.com/9391575/91791243-37208c80-ec45-11ea-920c-72ba023bd409.png)
看不到版本号信息
2:在win10上运行goctl   api go -api .\api\shorturl\shorturl.api -dir api
![image](https://user-images.githubusercontent.com/9391575/91791289-56b7b500-ec45-11ea-8548-a533bd61309a.png)

**Comment by kevwan** [comment]
1. 自行编译确实没有版本号的，你可以看goctl下的Makefile，make会带上当前时间作为版本号，直接go build是没有版本号的
2. 已经fix

**Comment by xhochipe** [comment]
tks
