### ISSUE TITLE
goctl 报错有误

### ISSUE THREAD

**Issue by wangzeping722** [tal-tech/go-zero#305]
读 goctl 源码的时候发现报错信息有一个小问题：
测试数据：
`
info(
    title: doc title
    desc: >
    doc description first part,
    doc description second part<
    version: 1.0
)

// TODO: test
// {
type Request struct {  // TODO: test
  // TODO
  Name func() ` + "`" + `path:"name,options=you|me"` + "`" + `   // }
} // TODO: test

// TODO: test
type Response struct {
  Message string ` + "`" + `json:"message"` + "`" + `
}

@server(
    // C0
	group: greet/s1
)
// C1
service A-api {
  // C2
  @server( // C3
    handler: GreetHandler
  )
  get /greet/from/:name(Request) returns (Response)   // hello
	
  // C4
  @handler NoResponseHandler  // C5
  get /greet/get(Request)
}
`
如何复现：
go test -v -test.run TestParser             
=== RUN   TestParser
    TestParser: gen_test.go:332: 
                Error Trace:    gen_test.go:332
                Error:          Expected nil, but got: &errors.errorString{s:"[func] - unsupported type, expr is unc() "}
                Test:           TestParser
--- FAIL: TestParser (0.00s)

错误信息是 `unc() ` ，应该是`func()`

**Comment by kingxt** [comment]
谢谢反馈，后续我们会对api解析采用antlr解析，解决提示不够友好问题。
