### ISSUE TITLE
关于goctl model  通配符 * 踩坑，建议

### ISSUE THREAD

**Issue by Code-Fight** [tal-tech/go-zero#306]
在语雀中goctl model 批量生成给的shell如下:

```
$ goctl model mysql ddl -src *.sql  -dir=./model
```
https://www.yuque.com/tal-tech/go-zero/nkg20f

如果用上面的语句去执行，那么并不能统配到所有sql文件。这个问题的原因可以去go-zero使用的cli库的issue中找到相关的资料。
参考：[这个链接](https://github.com/urfave/cli/issues/778)

ok，那么导致的问题就是，要么怀疑是个bug，要么自己去查下资料就能明白。

然后，在github 的example中，给的shell是

```
goctl model mysql ddl -src="./*.sql" -dir="./sql/model" -c
```

通过`“”`的方式干掉了shell的 * 匹配问题
其他方式参考：[这里](https://stackoverflow.com/questions/11456403/stop-shell-wildcard-character-expansion)

最后，建议直接把语雀上的跟github上的统一

**Comment by anqiansong** [comment]
> 感谢指正，这里通过添加双引号的形式去解决，文档已同步
