### ISSUE TITLE
build goctl got many errors

### ISSUE THREAD

**Issue by lupanagora** [tal-tech/go-zero#307]
./goctl.go:36:19: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:52:21: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:56:19: cannot use "github.com/urfave/cli".BoolFlag literal (type "github.com/urfave/cli".BoolFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".BoolFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:60:19: cannot use "github.com/urfave/cli".BoolFlag literal (type "github.com/urfave/cli".BoolFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".BoolFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:71:21: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:82:21: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:93:21: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:97:21: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:101:21: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:112:21: cannot use "github.com/urfave/cli".StringFlag literal (type "github.com/urfave/cli".StringFlag) as type "github.com/urfave/cli".Flag in array or slice literal:
	"github.com/urfave/cli".StringFlag does not implement "github.com/urfave/cli".Flag (Apply method has pointer receiver)
./goctl.go:112:21: too many errors

**Comment by kevwan** [comment]
GO111MODULE=on了吗？

**Comment by lupanagora** [comment]
OK,it works!
thx~
