### ISSUE TITLE
请教是否有 etcd 版本兼容问题

### ISSUE THREAD

**Issue by lupanagora** [tal-tech/go-zero#308]
/usr/local/Cellar/go@1.14/1.14.9/bin/go run hello.go
# go.etcd.io/etcd/clientv3/balancer/picker
/Users/myname/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20200402134248-51bdeb39e698/clientv3/balancer/picker/err.go:25:9: cannot use &errPicker literal (type *errPicker) as type Picker in return argument:
	*errPicker does not implement Picker (wrong type for Pick method)
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)
/Users/myname/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20200402134248-51bdeb39e698/clientv3/balancer/picker/roundrobin_balanced.go:33:9: cannot use &rrBalanced literal (type *rrBalanced) as type Picker in return argument:
	*rrBalanced does not implement Picker (wrong type for Pick method)
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)
# github.com/tal-tech/go-zero/zrpc/internal/balancer/p2c
/Users/myname/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/zrpc/internal/balancer/p2c/p2c.go:41:32: not enough arguments in call to base.NewBalancerBuilder
	have (string, *p2cPickerBuilder)
	want (string, base.PickerBuilder, base.Config)
/Users/myname/go/pkg/mod/github.com/tal-tech/go-zero@v1.1.1/zrpc/internal/balancer/p2c/p2c.go:58:9: cannot use &p2cPicker literal (type *p2cPicker) as type balancer.Picker in return argument:
	*p2cPicker does not implement balancer.Picker (wrong type for Pick method)
		have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
		want Pick(balancer.PickInfo) (balancer.PickResult, error)

**Comment by lupanagora** [comment]
这个是按照git demo 实现的hello 结构。无改动。
用go 1.12 版本，和go 1.14 均出现了上述etcd的问题
➜ tree .
├── etc
│   └── hello.yaml
├── go.mod
├── go.sum
├── hello
│   └── hello.pb.go
├── hello.go
├── hello.proto
├── helloclient
│   └── hello.go
└── internal
    ├── config
    │   └── config.go
    ├── logic
    │   └── pinglogic.go
    ├── server
    │   └── helloserver.go
    └── svc
        └── servicecontext.go

**Comment by kevwan** [comment]
使用 grpc 1.29.1

**Comment by lupanagora** [comment]
OK
