### ISSUE TITLE
goctl: cpu_linux.go error

### ISSUE THREAD

**Issue by bingoIsCoder** [tal-tech/go-zero#311]
现象：
运行goctl命令会出现如下的错误log：
`goctl -v
2020/12/24 19:31:53 {"@timestamp":"2020-12-24T19:31:53.584+08","level":"error","content":"cpu_linux.go:29 open cpuacct.usage_percpu: no such file or directory"}
goctl version 20201108 linux/amd64`

环境：
wsl ubuntu 1804
go: go version go1.15.3 linux/amd64

是否必现：是

**Comment by kevwan** [comment]
我在ubuntu 18.04下面跑goctl没有重现呢

```shell
[dev] ➜  goctl git:(master) docker run --rm -it -v `pwd`:/app -w /app ubuntu:18.04 bash
root@cd43036a4d2b:/app# ./goctl
NAME:
   goctl - a cli tool to generate code

USAGE:
   goctl [global options] command [command options] [arguments...]

VERSION:
   1.1.1 linux/amd64

COMMANDS:
   api       generate api related files
   docker    generate Dockerfile
   kube      generate kubernetes files
   rpc       generate rpc code
   model     generate model code
   config    generate config json
   template  template operation
   help, h   Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

**Comment by mengfei** [comment]
现象：
运行goctl命令会出现如下的错误log：
transform goctl rpc proto -src transform.proto -dir .
2020/12/31 17:12:38 {"@timestamp":"2020-12-31T17:12:38.501+08","level":"error","content":"cpu_linux.go:29 open cpuacct.usage_percpu: no such file or directory"}

环境：
wsl ubuntu 20.04
go: go version go1.15.3 linux/amd64

是否必现：是

**Comment by wxfvf** [comment]
我也是在WSL1 ubuntu18.04环境上，运行bookstore的例子也是出现类似的日志。且配置log的Level：error不生效，还是在控制台上打印info日志。
将wsl1转成wsl2之后，已经不报错，但是配置log的级别还是不生效。
![image](https://user-images.githubusercontent.com/63893554/103629503-5a54a300-4f7b-11eb-8ebd-2e180ac2971b.png)

**Comment by kevwan** [comment]
> 我也是在WSL1 ubuntu18.04环境上，运行bookstore的例子也是出现类似的日志。且配置log的Level：error不生效，还是在控制台上打印info日志。
> 将wsl1转成wsl2之后，已经不报错，但是配置log的级别还是不生效。
> ![image](https://user-images.githubusercontent.com/63893554/103629503-5a54a300-4f7b-11eb-8ebd-2e180ac2971b.png)

log改成Log

**Comment by forging2012** [comment]
在MacOS上发现类似错误。怀疑是MacOS和Linux文件系统不同导致的。
代码位置：https://github.com/zeromicro/go-zero/blob/a91c3907a8f68b6f08b1bad0125d7d5016105032/core/stat/internal/cgroup_linux.go

	data, err := iox.ReadText(path.Join(c.cgroups["cpuacct"], "cpuacct.usage_percpu"))


```
MacOS version：10.15.7 
Golang version：go version go1.17.7 darwin/amd64

➜  zero-admin git:(dev) ✗ ll /sys/fs/cgroup
ls: /sys/fs/cgroup: No such file or directory
```

建议做兼容性处理。

**Comment by ouranoshong** [comment]
Some change on cgroup v2：

     Cgroups v2 controllers
         The following controllers, documented in the kernel source file
         Documentation/admin-guide/cgroup-v2.rst (or
         Documentation/cgroup-v2.txt in Linux 4.17 and earlier), are
         supported in cgroups version 2:

         cpu (since Linux 4.15)
                This is the successor to the version 1 cpu and cpuacct
                controllers.
