### ISSUE TITLE
https 的协议需要在哪里配置？

### ISSUE THREAD

**Issue by banshour** [tal-tech/go-zero#33]
想改造成 https 协议的，可以配置实现吗

**Comment by kevwan** [comment]
`func StartHttps(host string, port int, certFile, keyFile string, handler http.Handler) error {
	addr := fmt.Sprintf("%s:%d", host, port)
	if server, err := buildHttpsServer(addr, handler, certFile, keyFile); err != nil {
		return err
	} else {
		return StartServer(server)
	}
}`

你可以fork了自己改，但我们把证书放在nginx层，所以没有在配置文件里支持

**Comment by kevwan** [comment]
```go
func StartHttps(host string, port int, certFile, keyFile string, handler http.Handler) error {
	addr := fmt.Sprintf("%s:%d", host, port)
	if server, err := buildHttpsServer(addr, handler, certFile, keyFile); err != nil {
		return err
	} else {
		return StartServer(server)
	}
}
```

你可以fork了自己改，但我们把证书放在nginx层，所以没有在配置文件里支持

**Comment by dongfenglong** [comment]
@kevwan 请问CertFile、KeyFile两参数使用相对路径可以吗？测试过程中始终没有测试信息。

**Comment by wensenz** [comment]
最新版本已经支持了， zhi yao只要配置了证书就可以了
<img width="1014" alt="image" src="https://github.com/zeromicro/go-zero/assets/10190672/a50309bf-5d42-4c45-9758-c689ee0331fb">

**Comment by wensenz** [comment]
在etc/xxx.yaml 配置

Host: 0.0.0.0
Port: 80
CertFile: etc/ca/xxxxx.crt
KeyFile: etc/ca/xxxxx.key

即可 ，亲测可用
