### ISSUE TITLE
goctl rpc 

### ISSUE THREAD

**Issue by mengfei** [tal-tech/go-zero#330]
执行命令goctl rpc proto -src transform.proto -dir . 
生成的目录结构与给出的示例不一样
![image](https://user-images.githubusercontent.com/2786763/103403798-64962c00-4b8c-11eb-8cae-34193e744755.png)

**Comment by mengfei** [comment]
![image](https://user-images.githubusercontent.com/2786763/103403854-9909e800-4b8c-11eb-93ed-46dd77d3fff9.png)
给出示例上的目录结构  
pb目录没有产生， 且文件transform.pd.go 在transform目录下， transformer目录中少了types.go

**Comment by kevwan** [comment]
新版本的文档没更新哈
