### ISSUE TITLE
是否有mongodb 的增删改查的范例。

### ISSUE THREAD

**Issue by MaxJohnXiang** [tal-tech/go-zero#334]
生成model文件的模板只有针对mysql的， 是否有针对mongodb 的。

**Comment by kevwan** [comment]
没有自动生成，但是mongo一样支持所有缓存功能。

后面会考虑加上自动生成。

**Comment by william-best** [comment]
建议支持mongodb

**Comment by william-best** [comment]
> 没有自动生成，但是mongo一样支持所有缓存功能。
> 
> 后面会考虑加上自动生成。

怎么支持有文档吗?

**Comment by kevwan** [comment]
你直接看core/stores/mongoc的包哈
