### ISSUE TITLE
core/syncx/shardcalls.go中done与delete优先级

### ISSUE THREAD

**Issue by Howie59** [tal-tech/go-zero#337]
https://github.com/tal-tech/go-zero/blob/fc43876cc591fb422943814efbb58bb8e2e68131/core/syncx/sharedcalls.go#L73

这个地方可以先调用done，然后再进行key的delete的

源码中wait()有如下注释：`Wait blocks until the WaitGroup counter is zero.`

**Comment by kevwan** [comment]
我看了下，没看出问题，能否说下有啥问题呢？

**Comment by Howie59** [comment]
> 我看了下，没看出问题，能否说下有啥问题呢？

是没问题的，我的意思是那两行注释可以去掉的

**Comment by kevwan** [comment]
> > 我看了下，没看出问题，能否说下有啥问题呢？
> 
> 是没问题的，我的意思是那两行注释可以去掉的

OK
