### ISSUE TITLE
wrong main file name when using goctl api

### ISSUE THREAD

**Issue by william-best** [tal-tech/go-zero#348]
goctl --version
goctl version 1.1.1 linux/amd64

command: 
goctl api go -api datacenter.api -dir .
ls
datacenter.api  etc  go.mod  internal  **votes.go**

expect： The main file  should be datacenter.go not votes.go

**Comment by william-best** [comment]
There's a little bit of confusion with your command design.
If people want use their own file name, goctl does not give a chance.
such as: goctl api go -api test.api -o main.go
My suggestion:

goctl api new --dir xxxx # create a dir
goctl api  -o test.api 
goctl api go --api test.api  --dir $path -o man.go

**Comment by kevwan** [comment]
this command generates couple files, if `-o` only specify one file, it doesn't make sense.
