### ISSUE TITLE
How to use @server

### ISSUE THREAD

**Issue by william-best** [tal-tech/go-zero#349]
There are 2 pages

https://www.yuque.com/tal-tech/go-zero/ze9i30#99de9344

```go
@server(
	jwt: $auth
	middleware: $middleware
)
service $name {
	....
}
```

https://www.yuque.com/tal-tech/go-zero/ppnpng#9d78a95e

```
service user-api {
    @server(  # what is the difference in/out service
        handler: CreateUserHandler   # how many keys in @server(handler/middleware/?) 
        group: user
    )
    post /api/users/create (createRequest)
}

@server(
    jwt: Auth
    group: profile
)
service user-api {...}
```

There are 2 questions in 2nd block.
If there is no different in/out service, I think @server  should be in service.

**Comment by kevwan** [comment]
@server is used to define service level.

**Comment by kingxt** [comment]
> There are 2 pages
> 
> https://www.yuque.com/tal-tech/go-zero/ze9i30#99de9344
> 
> ```go
> @server(
> 	jwt: $auth
> 	middleware: $middleware
> )
> service $name {
> 	....
> }
> ```
> 
> https://www.yuque.com/tal-tech/go-zero/ppnpng#9d78a95e
> 
> ```
> service user-api {
>     @server(  # what is the difference in/out service
>         handler: CreateUserHandler   # how many keys in @server(handler/middleware/?) 
>         group: user
>     )
>     post /api/users/create (createRequest)
> }
> 
> @server(
>     jwt: Auth
>     group: profile
> )
> service user-api {...}
> ```
> 
> There are 2 questions in 2nd block.
> If there is no different in/out service, I think @server should be in service.


We have update this doc, @server should be in service.
