### ISSUE TITLE
error: duplicated handler for name 

### ISSUE THREAD

**Issue by loki-zhou** [tal-tech/go-zero#355]
service user-api {
   ……
    @server(
        handler: GetUserHandler
        group: user
    )
    get /api/user/:name (getRequest) returns (getResponse)
}
service user-api {
   ……
    @server(
        handler: GetUserHandler
        group: userxxx
    )
    get /apixx/user/:name (getRequest) returns (getResponse)
}

我的handle 已经在不同group 下了，为什么不能一样？ 这种会报错
error: duplicated handler for name

**Comment by kevwan** [comment]
不同路由不能用同一个handler
