### ISSUE TITLE
请问 middleware 的功能对外开放吗？

### ISSUE THREAD

**Issue by Colstuwjx** [tal-tech/go-zero#356]
没找到这相关的文档，请问[这里](https://github.com/tal-tech/go-zero/blob/82d1ccf376bb3b20d9683a1abd65c970da88a6fd/rest/types.go#L6) middleware 部分是类似 gin 里面的 middleware ？

能否对外开放给用户用作自定义用途？

**Comment by kevwan** [comment]
middleware本来就是用来自定义中间件的哈

**Comment by Colstuwjx** [comment]
> middleware本来就是用来自定义中间件的哈

有相关的文档吗？

**Comment by kevwan** [comment]
https://www.yuque.com/tal-tech/go-zero/kpyuow

**Comment by linguanyuanA** [comment]
https://www.yuque.com/tal-tech/go-zero/kpyuow @kevwan  404 not found
