### ISSUE TITLE
goctl version

### ISSUE THREAD

**Issue by edieruby** [tal-tech/go-zero#358]
go-zero  v1.1.2
goctl is 1.1.1?  Is it right?
https://github.com/tal-tech/go-zero/blob/master/tools/goctl/goctl.go

goctl -v
goctl version 1.1.1 windows/amd64

**Comment by anqiansong** [comment]
> There is no direct connection between goctl and go-zero release version. The release version of go-zero will contain the new features released by the current version, including goctl and other core library updates, but goctl is only a tool update, but every time goctl is big Updates require a release from go-zero. Another function of the goctl version is that you can add instructions when raising issues, helping developers to quickly reproduce bugs and troubleshoot the specified version.

**Comment by kevwan** [comment]
we'll update goctl version in later releases.
