### ISSUE TITLE
只是单纯的使用api服务应该怎么组织结构目录呢?

### ISSUE THREAD

**Issue by LeeeMooo** [tal-tech/go-zero#363]
使用beego开发时不同的controllers文件夹划分不同的功能块, 现在有几百个api接口, 应该怎么组织文件代码呢?

```
├── etc
│   └── greet-api.yaml
├── go.mod
├── greet.api
├── greet.go
└── internal
    ├── config
    │   └── config.go
    ├── handler
    │   ├── greethandler.go
    │   └── routes.go
    ├── logic // 全部放在logic里面吗?
    │   └── greetlogic.go
    ├── svc
    │   └── servicecontext.go
    └── types
        └── types.go
```

**Comment by kevwan** [comment]
api这个目录层级去掉就好了

**Comment by LeeeMooo** [comment]
还有一个疑问, 有三个文件

- base.api
- a.api
- b.api
我在base.api里面import`a`和`b`, 然后`goctl api go -api base.api -dir .`
生成的文件是`b.go`, 不应该是base.go吗

**Comment by kingxt** [comment]
> 还有一个疑问, 有三个文件
> 
> * base.api
> * a.api
> * b.api
>   我在base.api里面import`a`和`b`, 然后`goctl api go -api base.api -dir .`
>   生成的文件是`b.go`, 不应该是base.go吗

xxx.go是根据service xxx 这个名字来的，而不是根据文件名来的。

**Comment by LeeeMooo** [comment]
> xxx.go是根据service xxx 这个名字来的，而不是根据文件名来的。

可能我没表述清楚

三个文件
![2021-01-08 15-02-00屏幕截图](https://user-images.githubusercontent.com/23691333/103984668-831aa980-51c2-11eb-9b01-4b737a28bed9.png)

`base.api`
![2021-01-08 15-07-29屏幕截图](https://user-images.githubusercontent.com/23691333/103985078-43a08d00-51c3-11eb-9522-7782e378a516.png)

`menu.api`
![2021-01-08 15-04-34屏幕截图](https://user-images.githubusercontent.com/23691333/103984854-dab91500-51c2-11eb-95c2-f0bca3b6dda4.png)

`user.api`
![2021-01-08 15-05-35屏幕截图](https://user-images.githubusercontent.com/23691333/103984946-00deb500-51c3-11eb-84b8-676e0892dd88.png)

`goctl api go -api base.api -dir .`

**Comment by LeeeMooo** [comment]
![2021-01-08 15-15-15屏幕截图](https://user-images.githubusercontent.com/23691333/103985674-549dce00-51c4-11eb-83a2-dd9e70aacd43.png)

**Comment by bob-sd** [comment]
我想知道，这个框架的使用说明在哪里？

**Comment by kevwan** [comment]
https://www.yuque.com/tal-tech/go-zero

**Comment by kevwan** [comment]
> > xxx.go是根据service xxx 这个名字来的，而不是根据文件名来的。
> 
> 可能我没表述清楚
> 
> 三个文件
> ![2021-01-08 15-02-00屏幕截图](https://user-images.githubusercontent.com/23691333/103984668-831aa980-51c2-11eb-9b01-4b737a28bed9.png)
> 
> `base.api`
> ![2021-01-08 15-07-29屏幕截图](https://user-images.githubusercontent.com/23691333/103985078-43a08d00-51c3-11eb-9522-7782e378a516.png)
> 
> `menu.api`
> ![2021-01-08 15-04-34屏幕截图](https://user-images.githubusercontent.com/23691333/103984854-dab91500-51c2-11eb-95c2-f0bca3b6dda4.png)
> 
> `user.api`
> ![2021-01-08 15-05-35屏幕截图](https://user-images.githubusercontent.com/23691333/103984946-00deb500-51c3-11eb-84b8-676e0892dd88.png)
> 
> `goctl api go -api base.api -dir .`

你需要在goctl api生成时指定生成目录
