### ISSUE TITLE
redis 支持 select 操作

### ISSUE THREAD

**Issue by shengdoushi** [tal-tech/go-zero#368]
redis 默认是第一个， 能否支持 select 选择其他的

**Comment by kevwan** [comment]
这种用法不符合最佳实践哈

**Comment by feng99** [comment]
> 这种用法不符合最佳实践哈

那Redis支持0-15个db的意义是什么?
阿里云买的话默认是0-255个db,为何这么设计呢?

**Comment by kevwan** [comment]
> > 这种用法不符合最佳实践哈
> 
> 那Redis支持0-15个db的意义是什么?
> 阿里云买的话默认是0-255个db,为何这么设计呢?

我的意思是不符合go-zero框架设计的最佳实践，存在即合理，这两个问题可以google哈

**Comment by gzlboy** [comment]
> > > 这种用法不符合最佳实践哈
> > 
> > 
> > 那Redis支持0-15个db的意义是什么?
> > 阿里云买的话默认是0-255个db,为何这么设计呢?
> 
> 我的意思是不符合go-zero框架设计的最佳实践，存在即合理，这两个问题可以google哈

真是傲娇
![021841DC](https://github.com/user-attachments/assets/a9a36110-9a4f-4d92-98a3-7d25b47c6485)
