### ISSUE TITLE
go get github.com/tal-tech/go-zero/tools/goctl  error

### ISSUE THREAD

**Issue by gyf19** [tal-tech/go-zero#39]
# github.com/tal-tech/go-zero/tools/goctl
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:32:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:43:21: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:47:19: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:51:19: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in slice literal:
	cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:63:21: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:74:21: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:85:21: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:89:21: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:100:21: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:104:21: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
gopath/src/github.com/tal-tech/go-zero/tools/goctl/goctl.go:104:21: too many errors

**Comment by kevwan** [comment]
GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/go-zero/tools/goctl
