### ISSUE TITLE
goctl rpc proto -src add.proto -dir . 错误， go mod 已经加了，生成api的时候没错误，怎么生成rpc时就报错了。

### ISSUE THREAD

**Issue by ninjashixuan** [tal-tech/go-zero#396]
protoc  -I=/home/shixuan/progo/rpc/add add.proto --go_out=plugins=grpc:/home/shixuan/progo/rpc/add/add
error: add.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

**Comment by yiGmMk** [comment]
same as i install protoc with version v3.0.0(that provide by ubuntu),with another version (v3.17.3) i solve it

**Comment by yiGmMk** [comment]
with command you can generate part file
