### ISSUE TITLE
gozero使用etcd 注册的 服务 能区分环境和版本吗？

### ISSUE THREAD

**Issue by mostamazing** [tal-tech/go-zero#400]
如题比如：user服务会上测试test，预发staging，生产prod 这三个环境，使用集中式的服务注册发现中心：etcd

当user服务新版需要上线时，要经过版本灰度部分pod按流量渐进上线。user1.0 --user1.0+gray（pod）

问题：一个K8S集群中，三个namespace 环境，一个集中的etcd，怎么管理上面三个环境 且能区分注册服务的版本？discov库哪里改呢？

**Comment by kevwan** [comment]
我们没有部署在用一个k8s集群里
