### ISSUE TITLE
cache.Cache和collection.Cache

### ISSUE THREAD

**Issue by 15951836388** [tal-tech/go-zero#406]
发现collection.Cache 并没有实现cache.Cache

希望可以实现cache.Cache

这样就可以在reids缓存和进程内缓存，方便的切换

**Comment by kevwan** [comment]
忘记回了，不好意思！

接口比较难统一，我看了，内存缓存是直接保存对象，redis是保存bytes的，导致接口不太一样哈

或者你改了试试？
