### ISSUE TITLE
同一个zrpcserver上，注册了多个rpc，配置要怎么填？

### ISSUE THREAD

**Issue by 15951836388** [tal-tech/go-zero#416]
![image](https://user-images.githubusercontent.com/14047483/105817320-69fe5f00-5ff0-11eb-99d4-b003ce76cc78.png)

现在配置里，貌似只能填一个rpc配置？ 能支持填在一起吗？是不是把etcd的key改成数组就行了？
![image](https://user-images.githubusercontent.com/14047483/105817868-2a844280-5ff1-11eb-943d-ca45918c90f0.png)

**Comment by kevwan** [comment]
一个server就是一个key哈

**Comment by fengxleon** [comment]
可以看看我修改的Demo，/fengxleon/bookstore
在一个server上注册了两个rpc
