### ISSUE TITLE
httpx OkJson方法修改建议

### ISSUE THREAD

**Issue by ycwmuyi** [tal-tech/go-zero#423]
![image](https://user-images.githubusercontent.com/13428737/106127343-6f4add80-6199-11eb-9fc2-e0933debd3fc.png)
建议添加一个对OKJson方法okJsonHandler逻辑，如上，方便对接口返回数据的统一结构封装

**Comment by kevwan** [comment]
哪里设置这个handler呢？

**Comment by ycwmuyi** [comment]
因为我需要一个这样的统一返回
```
type BaseReply struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
```
目前我对error做了统一的处理，如下：
```
	httpx.SetErrorHandler(func(err error) (int, interface{}) {
		if e, ok := err.(*shared.CodeError); ok {
			return http.StatusOK, types.BaseReply{
				Code: e.Code,
				Msg:  e.Error(),
			}
		}
		return http.StatusOK, types.BaseReply{
			Code: types.ErrorServerError.Code,
			Msg:  err.Error(),
		}
	})
```
然而对于正确的返回我只能通过下面这个方式处理
![image](https://user-images.githubusercontent.com/13428737/106549266-97489100-654b-11eb-9809-eaff0a96f41e.png)

我的建议是能否提供如下类似的方法：
```
	httpx.SetOkJsonHandler(func(resp interface) (int, interface{}) {
		return http.StatusOK, types.BaseReply{
				Code: CodeOk,
				Data:  resp
		}
	})
```
这样就能满足对统一返回结构的需求，或者是否有其他方式可以满足我的需求。

**Comment by kevwan** [comment]
你看看是否可以修改通过goctl模板来达成

**Comment by ycwmuyi** [comment]
好的 我试试

**Comment by lovemianhuatang** [comment]
httpx.SetOkJsonHandler 加这个可以统一处理，不用改模版在OkJson套一层，不考虑加一个吗？ @kevwan
