### ISSUE TITLE
关于executor

### ISSUE THREAD

**Issue by zhuxubin01** [tal-tech/go-zero#437]
executor看起来像是一个异步的任务,是否会出现pod重启导致任务丢失的情况?

是否可以考虑通过redis来实现即使pod重启或者服务器挂来,重启之后任务还能继续进行

**Comment by kevwan** [comment]
shutdown会全部执行掉的，除非这个任务执行时间很长

**Comment by zhuxubin01** [comment]
> shutdown会全部执行掉的，除非这个任务执行时间很长

了解,看到相关代码了
