### ISSUE TITLE
cannot find empty protobuf

### ISSUE THREAD

**Issue by william-best** [tal-tech/go-zero#444]
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto"

rpc get(google.protobuf.Empty) returns (Response);

❯ goctl rpc proto -src xxx.proto -dir . -style goZero
error: line 74:3, request type must defined in xxx.proto

protoc --version
libprotoc 3.13.0

**Comment by stepbystep2** [comment]
the same problem, help wanted
