### ISSUE TITLE
语雀“中台系统”，生成文件和文档不一致

### ISSUE THREAD

**Issue by fengxleon** [tal-tech/go-zero#461]
[《我是如何用go-zero 实现一个中台系统》](https://www.yuque.com/tal-tech/go-zero/kzpeey)
datacenter目录下 goctl api go -api datacenter.api -dir .
执行后没有datacenter.go和etc/datacenter-api.yaml，而是votes.go和etc/votes-api.yaml。

**Comment by kevwan** [comment]
文章作者明天会修改下文档，感谢反馈

**Comment by jackluo2012** [comment]
@fengxleon 请更新goctl 到最新的版本，我本地测试了下，是没有问题的,我目前的版本是: goctl version 1.1.4 darwin/amd64
更新方法: https://www.yuque.com/tal-tech/go-zero/tdsgkg
`
GO111MODULE=on GOPROXY=https://goproxy.cn/,direct go get -u github.com/tal-tech/go-zero/tools/goctl
`
`
➜  test git:(main) ✗ ls
datacenter.api search.api     user.api       votes.api
➜  test git:(main) ✗ goctl api go -api datacenter.api -dir .
Done.
➜  test git:(main) ✗ tree
.
├── datacenter.api
├── datacenter.go
├── etc
│   └── datacenter-api.yaml
├── internal
│   ├── config
│   │   └── config.go
│   ├── handler
│   │   ├── common
│   │   │   ├── appinfohandler.go
│   │   │   ├── qiuniutokenhandler.go
│   │   │   ├── snsinfohandler.go
│   │   │   └── wxtickethandler.go
│   │   ├── routes.go
│   │   ├── search
│   │   │   ├── articlehandler.go
│   │   │   ├── articleinithandler.go
│   │   │   └── articlestorehandler.go
│   │   ├── user
│   │   │   ├── code2sessionhandler.go
│   │   │   ├── loginhandler.go
│   │   │   ├── pinghandler.go
│   │   │   ├── registerhandler.go
│   │   │   ├── userinfohandler.go
│   │   │   └── wxloginhandler.go
│   │   └── votes
│   │       ├── activityicrviewhandler.go
│   │       ├── activityinfohandler.go
│   │       ├── enrollhandler.go
│   │       ├── enrollinfohandler.go
│   │       ├── enrolllistshandler.go
│   │       └── votehandler.go
│   ├── logic
│   │   ├── common
│   │   │   ├── appinfologic.go
│   │   │   ├── qiuniutokenlogic.go
│   │   │   ├── snsinfologic.go
│   │   │   └── wxticketlogic.go
│   │   ├── search
│   │   │   ├── articleinitlogic.go
│   │   │   ├── articlelogic.go
│   │   │   └── articlestorelogic.go
│   │   ├── user
│   │   │   ├── code2sessionlogic.go
│   │   │   ├── loginlogic.go
│   │   │   ├── pinglogic.go
│   │   │   ├── registerlogic.go
│   │   │   ├── userinfologic.go
│   │   │   └── wxloginlogic.go
│   │   └── votes
│   │       ├── activityicrviewlogic.go
│   │       ├── activityinfologic.go
│   │       ├── enrollinfologic.go
│   │       ├── enrolllistslogic.go
│   │       ├── enrolllogic.go
│   │       └── votelogic.go
│   ├── middleware
│   │   ├── admincheckmiddleware.go
│   │   └── usercheckmiddleware.go
│   ├── svc
│   │   └── servicecontext.go
│   └── types
│       └── types.go
├── search.api
├── user.api
└── votes.api

16 directories, 50 files
➜  test git:(main) ✗ goctl --version
goctl version 1.1.4 darwin/amd64
`

**Comment by fengxleon** [comment]
@kevwan @jackluo2012 感谢，我已经升级版本到goctl version 1.1.4 windows/amd64
另外，还有如下问题

> test git:(main) ✗ ls
> datacenter.api search.api user.api votes.api

这里需要把[《我是如何用go-zero 实现一个中台系统》](https://www.yuque.com/tal-tech/go-zero/kzpeey#6c1e2338)里的datacenter.api拆分成4个.api文件（文档里应该是3个，没有search？）吗？
1. 如果拆分，并分别执行.api文件，得到的文件目录和你提供的不一样。比如etc目录下有多个.yaml文件
2. 如果全部放在datacenter.api，执行时提示
```
datacenter>goctl api go -api datacenter.api -dir .
error: mulit service name defined user-api and datacenter-api
```

最后，还有一个问题，文档里有一个报错：
```
datacenter>goctl api go -api datacenter.api -dir .
error: datacenter.api line 52:46  extraneous input 'returns' expecting {'}', '@doc', '@handler', '@server'}
```

**Comment by jackluo2012** [comment]
@fengxleon 最近 更新了代码，你pull一下试试，如果是中台系统 有bug,请在那边提issues

**Comment by fengxleon** [comment]
是的，我看github上中台系统代码是新的。语雀那边文档是老早前的了 @jackluo2012
