### ISSUE TITLE
Error "go get -u github.com/tal-tech/go-zero"

### ISSUE THREAD

**Issue by Lining-Grab** [tal-tech/go-zero#464]
go: gopkg.in/cheggaaa/pb.v1@v1.0.29: go.mod has non-....v1 module path "github.com/cheggaaa/pb" at revision v1.0.29

Do we need to modify the go.mod, update to github.com/cheggaaa/pb?

**Comment by kevwan** [comment]
try GOMODULE111=on

**Comment by Lining-Grab** [comment]
It's a little odd. I remember I have set GOMODULE111=on, but it didn't work that time.
Whatever it works now.
Thank you!
