### ISSUE TITLE
啥时候搞个vue页面管理

### ISSUE THREAD

**Issue by RobinsChens** [tal-tech/go-zero#504]

**Comment by kevwan** [comment]
https://github.com/feihua/go-zero-admin-ui

**Comment by MaxToby** [comment]
我在做，可有兴趣参与。

**Comment by xiongdi9456** [comment]
> 我在做，可有兴趣参与。

有兴趣，反正我觉得很多朋友都要用

**Comment by xiongdi9456** [comment]
@MaxToby 怎么参与？

**Comment by ymego** [comment]
@MaxToby https://github.com/feihua/go-zero-admin-vue ,这个可以看看
