### ISSUE TITLE
error when runging greet example

### ISSUE THREAD

**Issue by PraflyGod** [tal-tech/go-zero#518]
Hi guys,

I tried to run the greet from the example but got error. Could you help me.
![image](https://user-images.githubusercontent.com/13954697/109007669-5d505200-76e7-11eb-949a-5c169f40dc18.png)

**Comment by kevwan** [comment]
please use go.mod instead of GOPATH

**Comment by PraflyGod** [comment]
![image](https://user-images.githubusercontent.com/13954697/109093981-40059d00-7754-11eb-8f5d-fc18ac282b38.png)
I am sure I had used go.mod. Still it didn't work.

**Comment by kevwan** [comment]
I think it's importing wrong packages.

see
`greet/home/yi/go_project/greet_example`

**Comment by PraflyGod** [comment]
But I did every steps as told by the instroduction. And the code is generated by the tools automatically。
So how could I configure the project and make it right?

**Comment by anqiansong** [comment]
Hi PraflyGod. I guess the GOPATH is `/home/yi/goroot/src`, and the root path of the project greet  is `/home/yi/goroot/src/greet/home/yi/go_project/greet_example/greet` where is recognized as a GOPATH project, therefore, the import path should like `greet/home/yi/go_project/greet_example/greet/*` in the root project greet. To avoid it, you can try the command `goctl api new greet` in any path rather than GOPATH. For the bug, we will fix it as soon as possibole.

**Comment by PraflyGod** [comment]
![image](https://user-images.githubusercontent.com/13954697/109253073-ed96b000-7829-11eb-8aef-980e776df652.png)
@anqiansong 
the greet directory isn't in the GOPATH

**Comment by anqiansong** [comment]
Try to execute `goctl api new greet` in another directory(do not in $GOROOT and $GOPATH), does it works?

**Comment by PraflyGod** [comment]
same error.

**Comment by kevwan** [comment]
would you please record the screen of the detail actions?

**Comment by PraflyGod** [comment]
I think I might find what the true problem is, my home dir is a soft link :
![image](https://user-images.githubusercontent.com/13954697/123191969-9c938180-d4d4-11eb-9227-82853a008da2.png)
![image](https://user-images.githubusercontent.com/13954697/123191983-a1583580-d4d4-11eb-8319-bb516a605b9e.png)
And the cmd "go list -json -m" runned in the program got different information with the one runned in terminal.  Please view the
pictures.

**Comment by kevwan** [comment]
@PraflyGod was the problem fixed? thanks!
