### ISSUE TITLE
关于使用postgresql的问题

### ISSUE THREAD

**Issue by kwotenp** [tal-tech/go-zero#534]
你好，在使用sqlx的过程中，发现postgresql不能支持。
go-zero/core/stores/sqlx/stmt.go  中的query函数中，调用的format的函数，只支持 问号 作为占位符，然而，在 github.com/lib/pq的driver中，是使用 $1,$2,$3...作为占位符，导致 format函数返回err
麻烦作者看一下这个问题，谢谢！

**Comment by kevwan** [comment]
收到

**Comment by kevwan** [comment]
fixed in 1.1.6
