### ISSUE TITLE
grpc升级一下呗

### ISSUE THREAD

**Issue by 78182648** [tal-tech/go-zero#536]
grpc升级一下呗，更新到最新稳定版本，现在好多项目都有冲突

**Comment by kevwan** [comment]
跟etcd冲突，要等etcd解决

**Comment by gyf19** [comment]
replace github.com/coreos/etcd => go.etcd.io/etcd/v3 v3.5.0-alpha.0

**Comment by kevwan** [comment]
> replace github.com/coreos/etcd => go.etcd.io/etcd/v3 v3.5.0-alpha.0

alpha release不会用到生产哈
