### ISSUE TITLE
不能用etcd自动去发现服务么？

### ISSUE THREAD

**Issue by zmbeex** [tal-tech/go-zero#550]
为什么要再网关配置每个微服务，而且不启动还会报错，只想启动2个了测试接口，还必须把所有微服务启动，这是我用的不对么？
能否只配置etcd，然后服务自己去发现配置

**Comment by kevwan** [comment]
支持etcd的

**Comment by MaxToby** [comment]
rest 启动时New Client Connection,当RPC服务未启动时Fatal。
 **所有依赖的服务必须在rest服务前启动。 这并不是etcd的问题**。
