### ISSUE TITLE
goctl v1.1.5版本bug，根据*.proto文件生成代码报错

### ISSUE THREAD

**Issue by Mikaelemmmm** [tal-tech/go-zero#553]
使用 goctl rpc proto -src *.proto -dir .  根据*.proto文件生成代码时候报错，错误信息如下：

error: 1:22: expected statement, found '<' (and 2 more errors)

**Comment by anqiansong** [comment]
@Mikaelemmmm 执行命令`goctl template clean` 清除一下模板，或者执行命令`goctl template revert -c rpc -name main.tpl`将该模板升级到最新，在 `1.1.5` 去除了rpc main 函数的顶部head(do not edit)信息

**Comment by housemecn** [comment]
建议合并到 https://go-zero.dev/error.html 这个页面中
