### ISSUE TITLE
生成model代码，缓存key删除遗漏

### ISSUE THREAD

**Issue by hutu1st** [tal-tech/go-zero#558]
当table中定义unique key时，model中生成的update方法，未删除unique key的缓存

**Comment by anqiansong** [comment]
Commits resolved it on Mar 11, 2021, see https://github.com/tal-tech/go-zero/pull/546/commits/218c230117a947fea4aeb09a68ed0ac892571f52

**Comment by hutu1st** [comment]
unique key 字段修改的话，还是无法删除吧 -，-

**Comment by anqiansong** [comment]
> unique key 字段修改的话，还是无法删除吧 -，-

那是的，只能主动过期！否则得把原来的值放进去。
