### ISSUE TITLE
docker构建失败 

### ISSUE THREAD

**Issue by brady-wang** [tal-tech/go-zero#559]
COPY failed: file not found in build context or excluded by .dockerignore: stat grid_address/cmd/api/etc: file does not exist
![image](https://user-images.githubusercontent.com/33504375/110885511-f30ff200-8321-11eb-99e8-e21c42f0a9a2.png)

![image](https://user-images.githubusercontent.com/33504375/110885476-df648b80-8321-11eb-9e06-24f40c5a2b5d.png)
目录是有这个文件的呀

**Comment by wantao666** [comment]
COPY ./etc /app/etc
