### ISSUE TITLE
为什么不用go/types.TypeString来拿这里的类型信息呢？

### ISSUE THREAD

**Issue by donnol** [tal-tech/go-zero#56]
https://github.com/tal-tech/go-zero/blob/52990550fb67a60278074a1aef5dd15871a33a89/tools/goctl/api/parser/typeparser.go#L186

就像：

```go
types.TypeString(xxx, qualifier)
```

**Comment by kingxt** [comment]
@donnol types.TypeString express golang type to string, and the typeparser.go method parseType will parse golang ast to inner type spec.
