### ISSUE TITLE
future: 希望zrpc client支持负载均衡

### ISSUE THREAD

**Issue by arch3754** [tal-tech/go-zero#567]
一个rpc 的client 支持轮询,权重,哈希,随机等方式去请求多个rpc server,同时支持各种重试的方式,例如failover这种

**Comment by kevwan** [comment]
已支持p2c负载均衡

**Comment by arch3754** [comment]
有计划支持多个client和多个server的这种方式吗?

**Comment by kevwan** [comment]
不太明白哈

> 有计划支持多个client和多个server的这种方式吗?

**Comment by arch3754** [comment]
例如: 目前有1个client和2个server, client轮询或随机请求到serverA和serverB,当请求serverA失败时failover到serverB

**Comment by kevwan** [comment]
已经是

**Comment by arch3754** [comment]
我测试两个server的时候,并没有平均的发送请求到serverA和serverB,而且都在A,当A挂了的时候才能到B

**Comment by arch3754** [comment]
我测试两个server的时候,并没有平均的发送请求到serverA和serverB,而是都在A,当A挂了的时候才能到B

**Comment by kevwan** [comment]
你看下p2c负载均衡，未必是2个就平均，长期动态平均

**Comment by arch3754** [comment]
![image](https://user-images.githubusercontent.com/16916249/111453731-dc690100-874e-11eb-85f4-8fd8b1a676e8.png)
当client到serverA异常时,并没有从serverB上拿下来数据,而是直接报错了

**Comment by kevwan** [comment]
异常有个检测时间，或者有过失败的请求才能降低权重

不报错就要自动重试
