### ISSUE TITLE
error: protoc-gen-go: unable to determine Go import path for "add.proto"

### ISSUE THREAD

**Issue by MichealJl** [tal-tech/go-zero#576]
error: protoc-gen-go: unable to determine Go import path for "add.proto"

![image](https://user-images.githubusercontent.com/31276367/112112727-d8c2f780-8bf0-11eb-9cd9-51b4938e5605.png)
有人遇到过么

**Comment by anqiansong** [comment]
@MichealJl 解决方案见文档https://zeromicro.github.io/go-zero/error.html，兼容问题我们尽快修复。

**Comment by lvyazhou** [comment]
option go_package = "add/";
add表示package包名路径；
