### ISSUE TITLE
error: context deadline exceeded, make sure rpc service "add.rpc" is alread started

### ISSUE THREAD

**Issue by chree188** [tal-tech/go-zero#578]
运行 `go run bookstore.go -f etc/bookstore-api.yaml` 错误
2021/03/24 12:00:59 rpc dial: discov://localhost:2379/add.rpc, error: context deadline exceeded, make sure rpc service "add.rpc" is alread started
exit status 1

**Comment by kevwan** [comment]
rpc和etcd起了吗？
