### ISSUE TITLE
互相调用的两个rpc 都启动不了，要求启动另一个，另一个也无法启动。怎么搞？

### ISSUE THREAD

**Issue by yijie8** [tal-tech/go-zero#581]
互相调用的两个rpc ，启动不了，要求启动另一个，另一个也无法启动。怎么搞？

rpc dial: discov://192.168.2.120:2379/article.rpc, error: context deadline exceeded, make sure rpc service "article.rpc" is alread started

**Comment by kevwan** [comment]
我觉得这是循环依赖问题，重新设计哈
