### ISSUE TITLE
empty etcd hosts

### ISSUE THREAD

**Issue by flanchegong** [tal-tech/go-zero#594]
empty etcd hosts

**Comment by kevwan** [comment]
what did you mean/

**Comment by flanchegong** [comment]
ctx := svc.NewServiceContext(c)

**Comment by wujunyi792** [comment]
how to fix it?

**Comment by 1045256143** [comment]
maybe you forget add the service conf to the etc yaml file

**Comment by 466919153** [comment]
empty etcd hosts  me too

**Comment by dahaipublic** [comment]
> 也许你忘记了将服务 conf 添加到 etc yaml 文件中

Name: identify.rpc
ListenOn: 0.0.0.0:9004

Etcd:
  Hosts:
    - etcd:2379
  Key: identify.rpc

Mysql:
  DataSource: root:123456@tcp(mysql:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: redis:6379
    Type: node
    Pass:

Salt: HWVOFkGgPTryzICwd7qnJaZR9KQ2i8xe

help me
