### ISSUE TITLE
重要的变量有自动透传的机制吗

### ISSUE THREAD

**Issue by CharellKing** [tal-tech/go-zero#597]
比如对于user_id，我放到context的某个特定key里面，自动的从gateway传递到调用链的任何地方；

**Comment by kevwan** [comment]
有的，我们也是通过context传user的

**Comment by CharellKing** [comment]
有例子么？

**Comment by CharellKing** [comment]
已经找到答案；https://pandaychen.github.io/2020/02/22/GRPC-METADATA-INTRO/
