### ISSUE TITLE
增加对mysql地理位置类型支持

### ISSUE THREAD

**Issue by weisttl** [tal-tech/go-zero#600]
sql字段：
` `location`  POINT COMMENT '位置',
`
报错：
`error: unexpected database type: point
`

**Comment by kevwan** [comment]
@anqiansong have a look

**Comment by anqiansong** [comment]
@weisttl 语法解析已经支持，但是不支持该类型接收，目前对于`point`我们没有找到好的类型进行数据库映射，是否有好的解决方案，可以参考一下，我将进一步优化。

**Comment by CsterKuroi** [comment]
any update?
