### ISSUE TITLE
declare two duplicate zrpc client for one key got context deadline exceeded

### ISSUE THREAD

**Issue by to2false** [tal-tech/go-zero#601]
I tried do as the following code, then i got ` rpc dial: discov://127.0.0.1:2379/xxxxxx, error: context deadline exceeded, make sure rpc service "xxxxxx" is alread started` when the execution reaches the second place
![image](https://user-images.githubusercontent.com/21302817/113682341-a12a7400-96f5-11eb-9916-52caccff341b.png)

**Comment by kevwan** [comment]
key conflict.

the error message is not accurate, I'll check it.

thanks for pointing out.

**Comment by tfzxyinhao** [comment]
init one client and then reused it in your business, don't dial one rpc server with the same key

**Comment by to2false** [comment]
> init one client and then reused it in your business, don't dial one rpc server with the same key

I already did that, just tried it before

**Comment by seyoatda** [comment]
遇到了同样的问题，同样的报错信息。所以目前这个 issue 是什么进展，错误信息有优化吗 ?

**Comment by kevwan** [comment]
你为啥会new两个一样的client呢？

**Comment by seyoatda** [comment]
> 你为啥会new两个一样的client呢？

因为是多人协作，所以在不同的地方同时生成同一个rpc的 client了，现在已经修复该问题。不过我比较好奇为啥为出现这种报错，是 go-zero的处理逻辑还是 grpc的处理逻辑？

**Comment by kevwan** [comment]
> > 你为啥会new两个一样的client呢？
> 
> 因为是多人协作，所以在不同的地方同时生成同一个rpc的 client了，现在已经修复该问题。不过我比较好奇为啥为出现这种报错，是 go-zero的处理逻辑还是 grpc的处理逻辑？

这肯定是go-zero处理的，不过我们对一个rpc server只会创建一个client，client里本身就有连接池，所以这个问题修好反而会让用户误创建多个client了

**Comment by hoysoft** [comment]
遇到同样问题：
   同一个rpc server，但需要分布各自处理30个地域的数据，但只能创建一个client，没法搞

**Comment by kevwan** [comment]
> 遇到同样问题： 同一个rpc server，但需要分布各自处理30个地域的数据，key分别是 a.log.rpc, b.log.rpc,c.log.rpc ......，但只支持创建一个client，没法搞

你应该共享一个client呀，不过我看看这个问题哈
