### ISSUE TITLE
goctl 通过-style 生成文件时问题

### ISSUE THREAD

**Issue by scopeccsky** [tal-tech/go-zero#610]
通过proto 生成rpc 文件时， 使用了
`goctl rpc proto -src fileName.proto -style goZero -dir . `
大部分文件和目录均按照 fileName的文件生成
其中， 生成了filenameclient目录及文件， 原本应该生成，fileNameClient
并且生成了fileName.yml的配置文件， 而main包fileName.go中，配置文件的引用为
`var configFile = flag.String("f", "etc/filename.yaml", "the config file")`
rpc的配置文件中的服务名字为“filename.rpc” 而不是“fileName.rpc”

通过api 生成文件
fileName.go的main包中， 引用了 fileName-api.yaml的配置文件，实际上生成的配置文件名为fileName-Api.yaml

**Comment by anqiansong** [comment]
在pr #684 中已经解决了
