### ISSUE TITLE
关于goctl template的几点建议

### ISSUE THREAD

**Issue by jan-bar** [tal-tech/go-zero#622]
1. 我一般先`goctl template init`初始化模板文件，然后编辑模板文件，文件管理器一般不会主动返回上级目录，因此在执行`goctl template update -c api`这种命令时会报错`error: open C:\Users\xxx\.goctl\api\main.tpl: Access is denied.`。报错原因是执行`goctl template update -c api`会先删除`C:\Users\xxx\.goctl\api`目录，但此时该目录被占用。**建议除了clean其他命令不删除目录，只删除目录下的文件。**
2. 另外看了源码`goctl template`只能使用默认目录，但是我有时候想要测试模板，有时候生成不同逻辑需要不同模板时。目前必须替换默认目录的模板文件。**可以考虑加一个参数指定模板文件路径，这样更加通用些。**

**Comment by anqiansong** [comment]
> 1. 我一般先`goctl template init`初始化模板文件，然后编辑模板文件，文件管理器一般不会主动返回上级目录，因此在执行`goctl template update -c api`这种命令时会报错`error: open C:\Users\xxx\.goctl\api\main.tpl: Access is denied.`。报错原因是执行`goctl template update -c api`会先删除`C:\Users\xxx\.goctl\api`目录，但此时该目录被占用。**建议除了clean其他命令不删除目录，只删除目录下的文件。**
> 2. 另外看了源码`goctl template`只能使用默认目录，但是我有时候想要测试模板，有时候生成不同逻辑需要不同模板时。目前必须替换默认目录的模板文件。**可以考虑加一个参数指定模板文件路径，这样更加通用些。**

已经在 #850 解决了
