### ISSUE TITLE
[示例错误] 函数瞎写了个FindOneByNumber，例子没法运行。

### ISSUE THREAD

**Issue by bingws** [tal-tech/go-zero#633]
业务代码中，登录逻辑，瞎写个FindOneByNumber()函数，model只有FindOne()。https://go-zero.dev/business-coding.html

**Comment by bingws** [comment]
一样的啊。还是没法运行。根本就没有FindOneByNumber方法好不好？
![image](https://user-images.githubusercontent.com/10806595/116342831-da966100-a815-11eb-9d4f-e7d77b80cf4e.png)

**Comment by anqiansong** [comment]
> 一样的啊。还是没法运行。根本就没有FindOneByNumber方法好不好？
> ![image](https://user-images.githubusercontent.com/10806595/116342831-da966100-a815-11eb-9d4f-e7d77b80cf4e.png)
> ![image](https://user-images.githubusercontent.com/10806595/116342951-0e718680-a816-11eb-9845-df3378c9a10c.png)
> 
> @anqiansong

@bingws  已修复，book.zip资源链接更新了。现在下载后重新生成即可。

**Comment by bingws** [comment]
还是不行，您那有这个示例的完整下载链接吗？@anqiansong

**Comment by bingws** [comment]
示例跑不通，没有学习的欲望了。。@anqiansong

**Comment by anqiansong** [comment]
@bingws  https://github.com/zeromicro/go-zero-demo

**Comment by gocpplua** [comment]
> @bingws 感谢反馈，是sql索引弄错了，已修复文件，请在 https://go-zero.dev/model-gen.html 文档中指示重新下载 `演示工程` 重新生成`usermodel.go`即可。

链接失效了
