### ISSUE TITLE
[goctl] 关于 goctl 工具以及配套的编辑器插件问题

### ISSUE THREAD

**Issue by smithyj** [tal-tech/go-zero#646]
目前觉得需要改进的地方，个人无能为力，不然就提 PR 了！
1、api 文件 import 不支持向上查找
2、api 文件使用 import 进来的 type 没有飘红
2、api 文件不能向 go 一样支持结构体嵌套，如下图，不支持嵌套
![image](https://user-images.githubusercontent.com/9820142/115580986-2e76e680-a2fa-11eb-8559-c7fdc2194d95.png)

**Comment by anqiansong** [comment]
@smithyj 感谢提出，对于你的3个问题
> 1.api 文件 import 不支持向上查找
> 2.api 文件使用 import 进来的 type 没有飘红

限于Idea插件优先级没有`goctl`高，目前暂时没有实现，目前还是以高亮提示为主，我们知道proto的插件也没有实现的，当然，我们会把这个纳入修复计划中。
> 3.api 文件不能向 go 一样支持结构体嵌套，如下图，不支持嵌套

api 的描述语言是由Go借鉴而来，但不完全和Go同步，因为这不仅仅是给写Go的开发人员阅读和开发。详情见 https://go-zero.dev/cn/api-grammar.html
