### ISSUE TITLE
关于redis 支持 db选择

### ISSUE THREAD

**Issue by kwotenp** [tal-tech/go-zero#655]
go-zero的redis模块，目前并不支持选择db。
是否考虑增加redis db的支持？ 建议 初始化redis的时候，增加 WithDB的选项。或者增加 Select方法，动态管理connection。
有时候并不是想要使用db，而是因为历史遗留项目使用了db 🌹

**Comment by kevwan** [comment]
```
r.Pipelined(func (pipe redis.Pipeliner) error {
    pipe.Do("select" ,1)
    return nil
}
```

**Comment by MexChina** [comment]
这个加到哪里呀

**Comment by kevwan** [comment]
> 这个加到哪里呀

执行redis其它指令之前哈

**Comment by zhangyangchen** [comment]
> > 这个加到哪里呀
> 
> 执行redis其它指令之前哈

程序首次启动时候，从mysql读出数据，通过pipe select 6 缓存到redis 是可以；等conn断开后，再次请求，会从mysql再次读出数据，缓存到redis db 0的现象
