### ISSUE TITLE
The command '/bin/sh -c go mod download' returned a non-zero code: 1

### ISSUE THREAD

**Issue by flanchegong** [tal-tech/go-zero#658]
root@zt-MS-7850:/home/go/src/enlightened# docker build -t common:rpcv1 -f service/common/cmd/rpc/Dockerfile .
Sending build context to Docker daemon     22MB
Step 1/20 : FROM golang:alpine AS builder
 ---> 270727b8fd0f
Step 2/20 : LABEL stage=gobuilder
 ---> Using cache
 ---> 278743597b7c
Step 3/20 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> 804336c49a3c
Step 4/20 : ENV GOOS linux
 ---> Using cache
 ---> e8cab9b84020
Step 5/20 : ENV GO111MODULE=on
 ---> Running in 9a1a476320e3
Removing intermediate container 9a1a476320e3
 ---> bfc2fbc44be7
Step 6/20 : ENV GOPROXY https://goproxy.cn,direct
 ---> Running in 2fb5e50487b8
Removing intermediate container 2fb5e50487b8
 ---> dda5bba3c34a
Step 7/20 : WORKDIR /build/zero
 ---> Running in 65453255eaf1
Removing intermediate container 65453255eaf1
 ---> de7a929b97b2
Step 8/20 : ADD go.mod .
 ---> c716d805b786
Step 9/20 : ADD go.sum .
 ---> c50fd41b1dda
Step 10/20 : RUN go mod download
 ---> Running in 626b9a203b39
go: github.com/RiverDanceGit/kdniaoGo@v1.0.0: Get "https://goproxy.cn/github.com/%21river%21dance%21git/kdniao%21go/@v/v1.0.0.mod": dial tcp: lookup goproxy.cn on 192.168.31.255:53: read udp 172.17.0.5:41192->192.168.31.255:53: i/o timeout
The command '/bin/sh -c go mod download' returned a non-zero code: 1

**Comment by kevwan** [comment]
这个是你网络问题，或者goproxy.cn不可用，我也解决不了哈

**Comment by flanchegong** [comment]
嗯，
