### ISSUE TITLE
COPY failed: stat /var/lib/docker/tmp/docker-builder108529658/common/cmd/rpc/etc: no such file or directory

### ISSUE THREAD

**Issue by flanchegong** [tal-tech/go-zero#659]
root@zt-MS-7850:/home/go/src/enlightened# docker build -t common:rpcv1 -f service/common/cmd/rpc/Dockerfile .
Sending build context to Docker daemon     22MB
Step 1/19 : FROM golang:alpine AS builder
 ---> 270727b8fd0f
Step 2/19 : LABEL stage=gobuilder
 ---> Using cache
 ---> 278743597b7c
Step 3/19 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> 804336c49a3c
Step 4/19 : ENV GOOS linux
 ---> Using cache
 ---> e8cab9b84020
Step 5/19 : ENV GO111MODULE=on     GOPROXY=https://goproxy.cn,direct
 ---> Using cache
 ---> 66a996bc1910
Step 6/19 : WORKDIR /build/zero
 ---> Using cache
 ---> 9749eca0c3ca
Step 7/19 : ADD go.mod .
 ---> Using cache
 ---> f7b4cf4907cb
Step 8/19 : ADD go.sum .
 ---> Using cache
 ---> 34fb6125d8b7
Step 9/19 : RUN go mod download
 ---> Using cache
 ---> 7caac7f9e862
Step 10/19 : COPY . .
 ---> Using cache
 ---> 0dd6c5f13985
Step 11/19 : COPY common/cmd/rpc/etc /app/etc
COPY failed: stat /var/lib/docker/tmp/docker-builder108529658/common/cmd/rpc/etc: no such file or directory

**Comment by feihua** [comment]
是不是漏了service



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月28日(星期三) 晚上8:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [tal-tech/go-zero] COPY failed: stat /var/lib/docker/tmp/docker-builder108529658/common/cmd/rpc/etc: no such file or directory (#659)





 
***@***.***MS-7850:/home/go/src/enlightened# docker build -t common:rpcv1 -f service/common/cmd/rpc/Dockerfile .
 Sending build context to Docker daemon     22MB
 Step 1/19 : FROM golang:alpine AS builder
 ---&gt; 270727b8fd0f
 Step 2/19 : LABEL stage=gobuilder
 ---&gt; Using cache
 ---&gt; 278743597b7c
 Step 3/19 : ENV CGO_ENABLED 0
 ---&gt; Using cache
 ---&gt; 804336c49a3c
 Step 4/19 : ENV GOOS linux
 ---&gt; Using cache
 ---&gt; e8cab9b84020
 Step 5/19 : ENV GO111MODULE=on     GOPROXY=https://goproxy.cn,direct
 ---&gt; Using cache
 ---&gt; 66a996bc1910
 Step 6/19 : WORKDIR /build/zero
 ---&gt; Using cache
 ---&gt; 9749eca0c3ca
 Step 7/19 : ADD go.mod .
 ---&gt; Using cache
 ---&gt; f7b4cf4907cb
 Step 8/19 : ADD go.sum .
 ---&gt; Using cache
 ---&gt; 34fb6125d8b7
 Step 9/19 : RUN go mod download
 ---&gt; Using cache
 ---&gt; 7caac7f9e862
 Step 10/19 : COPY . .
 ---&gt; Using cache
 ---&gt; 0dd6c5f13985
 Step 11/19 : COPY common/cmd/rpc/etc /app/etc
 COPY failed: stat /var/lib/docker/tmp/docker-builder108529658/common/cmd/rpc/etc: no such file or directory

**Comment by flanchegong** [comment]
有的哦：docker build -t common:rpcv1 -f service/common/cmd/rpc/Dockerfile .

**Comment by kevwan** [comment]
你这个是有etc目录吗？

**Comment by flanchegong** [comment]
service/common/cmd/rpc/etc

**Comment by kevwan** [comment]
goctl版本是啥？

**Comment by flanchegong** [comment]
goctl version 1.1.6 linux/amd64

**Comment by flanchegong** [comment]
可以了，感谢大神kevwan，亲自指导
[root@ecs-1839-6d17 enlightened]# docker build -t common:rpcv1 -f service/common/cmd/rpc/Dockerfile .
Sending build context to Docker daemon  403.5MB
Step 1/19 : FROM golang:alpine AS builder
alpine: Pulling from library/golang
540db60ca938: Pull complete 
adcc1eea9eea: Pull complete 
4c4ab2625f07: Pull complete 
c5e7595549f7: Pull complete 
3df88182f7ac: Pull complete 
Digest: sha256:4dd403b2e7a689adc5b7110ba9cd5da43d216cfcfccfbe2b35680effcf336c7e
Status: Downloaded newer image for golang:alpine
 ---> 722a834ff95b
Step 2/19 : LABEL stage=gobuilder
 ---> Running in 3261a97feb55
Removing intermediate container 3261a97feb55
 ---> 700b16b55387
Step 3/19 : ENV CGO_ENABLED 0
 ---> Running in 95c5f955d47c
Removing intermediate container 95c5f955d47c
 ---> b907097f133b
Step 4/19 : ENV GOOS linux
 ---> Running in d68233b05b4d
Removing intermediate container d68233b05b4d
 ---> 67b315a4cda2
Step 5/19 : ENV GO111MODULE=on     GOPROXY=https://goproxy.cn,direct
 ---> Running in 138c98359c00
Removing intermediate container 138c98359c00
 ---> da16c7acac47
Step 6/19 : WORKDIR /build/zero
 ---> Running in 16afa310d1cb
Removing intermediate container 16afa310d1cb
 ---> 767b992616da
Step 7/19 : ADD go.mod .
 ---> 508d5f1cd927
Step 8/19 : ADD go.sum .
 ---> 5c7466db08cf
Step 9/19 : RUN go mod download
 ---> Running in 04e8daf74dbd
Removing intermediate container 04e8daf74dbd
 ---> 21cf3befe549
Step 10/19 : COPY . .
 ---> 3789832d1f95
Step 11/19 : COPY service/common/cmd/rpc/etc /app/etc
 ---> 2cc340588a15
Step 12/19 : RUN go build -ldflags="-s -w" -o /app/common service/common/cmd/rpc/common.go
 ---> Running in 6b6016069f29
Removing intermediate container 6b6016069f29
 ---> fdda3ed589ab
Step 13/19 : FROM alpine
latest: Pulling from library/alpine
540db60ca938: Already exists 
Digest: sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f
Status: Downloaded newer image for alpine:latest
 ---> 6dbb9cc54074
Step 14/19 : RUN apk update --no-cache && apk add --no-cache ca-certificates tzdata
 ---> Running in fce5ec8d6e59
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: Permission denied
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
v3.13.5-95-g640af164dc [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
OK: 9210 distinct packages available
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/2) Installing ca-certificates (20191127-r5)
(2/2) Installing tzdata (2021a-r0)
Executing busybox-1.32.1-r6.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 10 MiB in 16 packages
Removing intermediate container fce5ec8d6e59
 ---> 6d0c99d0906c
Step 15/19 : ENV TZ Asia/Shanghai
 ---> Running in 630113d35c3e
Removing intermediate container 630113d35c3e
 ---> a5f6fe3cd1ff
Step 16/19 : WORKDIR /app
 ---> Running in 994139373e04
Removing intermediate container 994139373e04
 ---> 12994e7bca96
Step 17/19 : COPY --from=builder /app/common /app/common
 ---> 4bc47e75d966
Step 18/19 : COPY --from=builder /app/etc /app/etc
 ---> ffab03acab99
Step 19/19 : CMD ["./common", "-f", "etc/common.yaml"]
 ---> Running in 2b1844f3163f
Removing intermediate container 2b1844f3163f
 ---> 3f4c6fd2dcf3
Successfully built 3f4c6fd2dcf3
Successfully tagged common:rpcv1
