### ISSUE TITLE
提供admin插件可以支持系统状态的查看监控

### ISSUE THREAD

**Issue by dlmufei** [tal-tech/go-zero#66]
提供admin可选插件可以直接支持系统状态的简单查看监控，作为一个独立框架感觉会更完善

**Comment by kevwan** [comment]
> 提供admin可选插件可以直接支持系统状态的简单查看监控，作为一个独立框架感觉会更完善

不太懂，请详细解释下哈

**Comment by kevwan** [comment]
是说prometheus这样的工具来查看状态嘛？
https://github.com/tal-tech/go-zero/blob/master/doc/metric.md

**Comment by loocor** [comment]
> 是说prometheus这样的工具来查看状态嘛？
> https://github.com/tal-tech/go-zero/blob/master/doc/metric.md

是不是提供整个系统的 Dashboard？
另外，这个链接已经丢失了无法访问。
