### ISSUE TITLE
建议goctl可以用json生成api文件

### ISSUE THREAD

**Issue by superlbr** [tal-tech/go-zero#675]
就项目迁移来说，json很自然的前后端数据

**Comment by superlbr** [comment]
1. 既然goctl可以生成ts，那也可以从ts生成api文件
2. 用json是觉得ts有点啰嗦，
```
couponItem: {
   name: '五一特惠',
   price: 12.0,
}
```
类似这样的json格式，可以直接推导类型
当然可以做一些增强，比如
```
   status: {
     type: Boolean,
     default: false,
   }
```
3. 类似postman，给个接口合集，goctl如果可以自动全部生成出来，岂不是很方便

**Comment by kevwan** [comment]
话虽这么说，但是我们只打算支持从api文件生成，如果ts生成api文件，那么java应该也可以生成嘛
