### ISSUE TITLE
r.Context().Value("uid")不能获取定义在jwt里面的参数

### ISSUE THREAD

**Issue by vorfreudeCode** [tal-tech/go-zero#687]
按照文档使用jwt鉴权，需要获取当前用户的信息，返回nil
![image](https://user-images.githubusercontent.com/12755519/118267483-ba8dbf80-b4ee-11eb-8fdb-04b257fcab9e.png)
![image](https://user-images.githubusercontent.com/12755519/118267720-17897580-b4ef-11eb-81d7-41f84b876b18.png)

**Comment by vorfreudeCode** [comment]
解决了

**Comment by kevwan** [comment]
咋解决的？

**Comment by daniuEvan** [comment]
咋解决的？我也遇到了！

**Comment by daniuEvan** [comment]
> 按照文档使用jwt鉴权，需要获取当前用户的信息，返回nil
> ![image](https://user-images.githubusercontent.com/12755519/118267483-ba8dbf80-b4ee-11eb-8fdb-04b257fcab9e.png)
> ![image](https://user-images.githubusercontent.com/12755519/118267720-17897580-b4ef-11eb-81d7-41f84b876b18.png)

老哥，你是怎么解决的？我也遇到了这个问题

**Comment by daniuEvan** [comment]
My problem : my interface JWT authentication was added later, but I only deleted the logic code. I cleared the handler and SVC and regenerated the code

**Comment by daniuEvan** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> How did you solve it? Me too!

My problem : my interface JWT authentication was added later, but I only deleted the logic code. I cleared the handler and SVC and regenerated the code
