### ISSUE TITLE
关于handler的问题请教

### ISSUE THREAD

**Issue by xhochipe** [tal-tech/go-zero#693]
![image](https://user-images.githubusercontent.com/9391575/118443103-168a5b00-b71e-11eb-9029-ca1babbdf748.png)

如上图,我handler在不同的分组,然后提示Views是重复的, 怎么可以在不同分组里面写curd的时候handler可以顶成一样的,这样好区分,
还有一个问题：
生成的本身就在handler和logic目录下了,下面的生成文件名的时候怎么能去掉文件名的后面部分 handler和logic

**Comment by kingxt** [comment]
谢谢你的建议，不过我觉得最好是不要这么弄，因为api还需要给客户端使用，名字一样会导致隐形的沟通成本。

**Comment by xhochipe** [comment]
@kevwan 不好意思，网卡了，然后我以为没法出去，就改了下标题

**Comment by xhochipe** [comment]
@kingxt 你指的是给比如前端这样的同学用吗，不是可以生成api文档吗，或者给他们直接给api，这样应该可以避免沟通成本吧，这个api描述文档只是给后端用来开发的

**Comment by kingxt** [comment]
> @kingxt 你指的是给比如前端这样的同学用吗，不是可以生成api文档吗，或者给他们直接给api，这样应该可以避免沟通成本吧，这个api描述文档只是给后端用来开发的

前端也是直接生成代码，如果用Group+handler这种方式生成handler，问题在于又多了一层需要解释的，除非将struct分成不同文件夹。

**Comment by xhochipe** [comment]
@kingxt 我理解你的意思了，其实如果将types下的也生成的时候按照group分成目录，这样api描述文件，handler可以复用，其次logic和handler下面生成文件名的时候 比如xxx_handler.go  xxx_logic.go ，其实都是在handler目录下和logic目录下了，感觉文件名 handler/xxx.go   logic/xxx.go 这样个人感觉比较直接点

**Comment by kingxt** [comment]
> @kingxt 我理解你的意思了，其实如果将types下的也生成的时候按照group分成目录，这样api描述文件，handler可以复用，其次logic和handler下面生成文件名的时候 比如xxx_handler.go xxx_logic.go ，其实都是在handler目录下和logic目录下了，感觉文件名 handler/xxx.go logic/xxx.go 这样个人感觉比较直接点

我们内部考虑下，如果你迫切需要这样弄，你可以写一个简单插件解决。

**Comment by xhochipe** [comment]
@kingxt 嗯嗯，谢谢
