### ISSUE TITLE
关于代码生成模板api中handler问题

### ISSUE THREAD

**Issue by xhochipe** [tal-tech/go-zero#695]
![image](https://user-images.githubusercontent.com/9391575/118443103-168a5b00-b71e-11eb-9029-ca1babbdf748.png)

如上图,我handler在不同的分组,然后提示Views是重复的, 怎么可以在不同分组里面写curd的时候handler可以写成一样的,这样好区分,
还有一个问题：
生成的本身就在handler和logic目录下了,下面的生成文件名的时候怎么能去掉文件名的后面部分 handler和logic

**Comment by kevwan** [comment]
不要重复创建呀，一个问题发了3个issue

duplicate #693
