### ISSUE TITLE
redis 怎么配置用哪个DB?

### ISSUE THREAD

**Issue by mme1** [tal-tech/go-zero#715]
redis怎么配置用哪个DB呢？我看代码是写死的  DB 0 

`package redis

import (
	"io"

	red "github.com/go-redis/redis"
	"github.com/tal-tech/go-zero/core/syncx"
)

const (
	defaultDatabase = 0
	maxRetries      = 3
	idleConns       = 8
)

var clientManager = syncx.NewResourceManager()

func getClient(server, pass string) (*red.Client, error) {
	val, err := clientManager.GetResource(server, func() (io.Closer, error) {
		store := red.NewClient(&red.Options{
			Addr:         server,
			Password:     pass,
			DB:           defaultDatabase,
			MaxRetries:   maxRetries,
			MinIdleConns: idleConns,
		})
		store.WrapProcess(process)
		return store, nil
	})
	if err != nil {
		return nil, err
	}

	return val.(*red.Client), nil
}
`

**Comment by kevwan** [comment]
可以用pipeline去执行select

**Comment by kevwan** [comment]
用多个DB不是最佳实践，尽可能不用哈
