### ISSUE TITLE
rpc怎么写单元测试 没找到文档

### ISSUE THREAD

**Issue by leafmirror** [tal-tech/go-zero#721]
rpc怎么写单元测试 没找到文档

**Comment by kevwan** [comment]
google grpc unit test

**Comment by seth-shi** [comment]
https://github.com/seth-shi/go-zero-testing-example
![image](https://github.com/user-attachments/assets/b702be70-3b31-48a3-bfc7-70d7b2c5f2c0)
朋友们可以参考一下这个项目.
