### ISSUE TITLE
logx

### ISSUE THREAD

**Issue by flanchegong** [tal-tech/go-zero#722]
error: value "file" is not defined in options "[dev test rt pre pro]"

**Comment by kevwan** [comment]
file is for logx Mode, [dev test rt pre pro] is for service

put logx Mode in **Log** item.

**Comment by flanchegong** [comment]
c := logx.LogConf{
		Mode: "console",
		Path: "logs",
	}
	logx.MustSetup(c)
	defer logx.Close()
