### ISSUE TITLE
rest.Server 能否对外提供 `Shutdown` 方法？

### ISSUE THREAD

**Issue by rehth** [tal-tech/go-zero#727]
直接实现或者对外暴露 `http.Server` 的  `Shutdown` 方法？

这样在实现服务关闭时，可以更加友好

**Comment by kevwan** [comment]
什么场景更友好呢？

**Comment by rehth** [comment]
比如说监听某个信号后，需要对服务器进行关闭操作，这时按逻辑服务器应该调用 `Shoutdown`方法

**Comment by kevwan** [comment]
这个go-zero已经做了

**Comment by rehth** [comment]
> 这个go-zero已经做了

已经有计划了吗？主要是在学习时发现目前只有在执行异常时才会执行`Shutdown`方法

![IMG_20210529_120828.jpg](https://user-images.githubusercontent.com/33532657/120057560-98f81080-c076-11eb-91e2-412bfa0877f7.jpg)

**Comment by kevwan** [comment]
收到SIGTERM信号就会执行Shutdown

**Comment by rehth** [comment]
> 收到SIGTERM信号就会执行Shutdown

只有`SIGTERM`信号吗？如果是`SIGINT` 或者`SIGKILL`会怎么样?
