### ISSUE TITLE
docker 运行报 找不到文件？

### ISSUE THREAD

**Issue by shenmingxing** [tal-tech/go-zero#73]
![image](https://user-images.githubusercontent.com/35058335/93062234-3fe27b00-f6a7-11ea-94c6-d5e4bb2cf210.png)
![Uploading image.png…]()

**Comment by kevwan** [comment]
这个不是go-zero的问题吧？

**Comment by shenmingxing** [comment]
不是大佬的问题。但是我就跑的stat下面的Dockerfile，运行找不到。你们打包运行的时候是否有遇到？

**Comment by dylanNew** [comment]
可以看下你的 go build 和 docker build 的命令吗？

**Comment by shenmingxing** [comment]
stat 目录下 go build -o cpu . ;docker build gz:v1.0 .

**Comment by kevwan** [comment]
跟go-zero不想关的不要在这里提issue哈
