### ISSUE TITLE
mongo模块中的MustNewModel方法不能传入指定数据库名称参数

### ISSUE THREAD

**Issue by linuxdrake** [tal-tech/go-zero#734]
go-zero框架中的cores里的stores中，在mongo模块里的model.go文件定义了MustNewModel方法，该方法原型如下：
// MustNewModel returns a Model, exits on errors.
func MustNewModel(url, collection string, opts ...Option) *Model {
	model, err := NewModel(url, collection, opts...)
	if err != nil {
		log.Fatal(err)
	}

	return model
}

// NewModel returns a Model.
func NewModel(url, collection string, opts ...Option) (*Model, error) {
	session, err := getConcurrentSession(url)
	if err != nil {
		return nil, err
	}

	return &Model{
		session: session,
		**// If name is empty, the database name provided in the dialed URL is used instead_**
		db:         session.DB(""),
		collection: collection,
		brk:        breaker.GetBreaker(url),
		opts:       opts,
	}, nil
}
其中，调用了下面的NewModel函数, db: session.DB(""),默认为空，如果我想传入一个指定的数据库名称，如何传入参数呢？
请教，是否可以修改可以传入数据库名称参数。

**Comment by miaogaolin** [comment]
url参数中设置数据库名称！
url连接语法：`mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]`
