### ISSUE TITLE
go-zero对mongo的model生成不友好

### ISSUE THREAD

**Issue by linuxdrake** [tal-tech/go-zero#735]
rpc开发时，我在go文件中定义了mongo的集合，例如
type User  struct{
   name string `json:"name"`
}

type Person struct{
  id bson.ObjectId `json:"_id"`
  code string `json:"code"`
}

goctl model mongo 命令只生成一个struct的model文件，第二个Person没有生成相应的代码

**Comment by anqiansong** [comment]
@linuxdrake `goctl model mongo` 的 `--type` 是一个sliceflag，你可以通过 `goctl model mongo -t User -t Person -dir .`  指定多个 `Type`
