### ISSUE TITLE
官方生成的rpc 编译有问题，建议把pb目录transform  名称换成pb

### ISSUE THREAD

**Issue by Mike-li123** [tal-tech/go-zero#737]
[dev@audio-chat-dev-000 /data/mike/shorturl/rpc/transform]$ ll
total 64K
drwxrwxr-x 2 dev dev 4.0K May 28 08:05 etc
-rw-rw-r-- 1 dev dev  335 May 28 08:09 go.mod
-rw-rw-r-- 1 dev dev  36K May 28 08:09 go.sum
drwxrwxr-x 6 dev dev 4.0K May 28 08:05 internal
drwxrwxr-x 2 dev dev 4.0K May 28 08:05 transform
drwxrwxr-x 2 dev dev 4.0K May 28 08:05 transformer
-rw-rw-r-- 1 dev dev  707 May 28 08:05 transform.go
-rw-rw-r-- 1 dev dev  345 May 28 08:04 transform.proto
[dev@audio-chat-dev-000 /data/mike/shorturl/rpc/transform]$ pwd
/data/mike/shorturl/rpc/transform
[dev@audio-chat-dev-000 /data/mike/shorturl/rpc/transform]$ go build
go build: build output "transform" already exists and is a directory
[dev@audio-chat-dev-000 /data/mike/shorturl/rpc/transform]$ cat go.mod 
module transform

go 1.15

require (
        github.com/go-sql-driver/mysql v1.6.0 // indirect
        github.com/golang/protobuf v1.5.2
        github.com/iancoleman/strcase v0.1.3 // indirect
        github.com/tal-tech/go-zero v1.1.7
        github.com/zeromicro/antlr v1.0.0 // indirect
        go.uber.org/automaxprocs v1.4.0 // indirect
        google.golang.org/grpc v1.38.0
)
[dev@audio-chat-dev-000 /data/mike/shorturl/rpc/transform]$ ll transform
total 12K
-rw-rw-r-- 1 dev dev 11K May 28 08:05 transform.pb.go
[dev@audio-chat-dev-000 /data/mike/shorturl/rpc/transform]$ 

[dev@audio-chat-dev-000 /data/mike/shorturl/rpc/transform]$ goctl --version
goctl version 1.1.6 linux/amd64

**Comment by anqiansong** [comment]
@Mike-li123 这里介绍了为什么会这么生成。https://go-zero.dev/cn/rpc-dir.html
