### ISSUE TITLE
有打算实现配置中心的功能吗？

### ISSUE THREAD

**Issue by panh1992** [tal-tech/go-zero#741]
不同环境的配置管理非常费心，希望给出相关实例

**Comment by ldmid666** [comment]
比如接入apollo？官方有计划吗

**Comment by kevwan** [comment]
> 比如接入apollo？官方有计划吗

暂无计划哈

**Comment by leafmirror** [comment]
> 比如接入apollo？官方有计划吗

apollo 自己接就可以 不用改代码  叫运维配下
