### ISSUE TITLE
core/sync/sharecalls.go

### ISSUE THREAD

**Issue by buptlmk** [tal-tech/go-zero#742]
core/sync/sharecalls.go 71行的makecall函数，注释我认为没有必要一定让c.wg.Done()放在delete之后，这并不影响wg.wait(),相反放在delete前面会更好：
1、当delete后，又来一个同样key的请求，需要重新执行
2、放在delete前，来了新的同样key的请求可以直接返回
3、可以更快地响应，delete需要锁竞争
![image](https://user-images.githubusercontent.com/47209369/120164603-5462a580-c22d-11eb-8464-3eb141c34e18.png)

**Comment by kevwan** [comment]
这是个level trigger，如果是edge trigger的话，那么就得原来的写法，我还是比较趋向于不依赖标准库的level trigger.
