### ISSUE TITLE
goctl model mysql不能生成代码

### ISSUE THREAD

**Issue by william-best** [tal-tech/go-zero#745]
1. 最新版位v1.1.7， 但go get goctl是v1.1.6
2. 使用workbench生成sql,其中包含三个表， 总是提示错误
 goctl model mysql ddl -src="./*.sql" -dir="./sql/model" 
error: syntax error at position 461 near 'drop
3. 只有把包含三个table的sql文件，删的只剩一个table才能创建成功。
4. https://github.com/jackluo2012/datacenter/blob/main/sql.sql   这个也是使用的go-zero， 也不能生成代码， 同样使用v1.1.6

**Comment by wangerzi** [comment]
直接手动执行 SQL 有问题吗，看起来跟这个 ISSUE 描述的问题有点像 https://github.com/tal-tech/go-zero/issues/745

**Comment by william-best** [comment]
> 直接手动执行 SQL 有问题吗，看起来跟这个 ISSUE 描述的问题有点像 #745

SQL建表都没问题。 直接workbench导出的。

**Comment by william-best** [comment]
那应当改进一下， 毕竟这是官方直接导出来的sql，还是有用的。

**Comment by william-best** [comment]
UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,

**Comment by wangerzi** [comment]
@william-best 应该是的，我之前也遇到类似的，官方建议用 datasource 的形式去做自动生成，https://github.com/tal-tech/go-zero/issues/740#issuecomment-851781769

**Comment by kevwan** [comment]
> @william-best 应该是的，我之前也遇到类似的，官方建议用 datasource 的形式去做自动生成，[#740 (comment)](https://github.com/tal-tech/go-zero/issues/740#issuecomment-851781769)

对的，因为要解析对还是比较麻烦，要换库才行，我们本来内网有个web界面，直接让选择哪个库，一键生成然后copy出来的

**Comment by william-best** [comment]
> > @william-best 应该是的，我之前也遇到类似的，官方建议用 datasource 的形式去做自动生成，[#740 (comment)](https://github.com/tal-tech/go-zero/issues/740#issuecomment-851781769)
> 
> 对的，因为要解析对还是比较麻烦，要换库才行，我们本来内网有个web界面，直接让选择哪个库，一键生成然后copy出来的

我今天使用datasource的方式， 只不过多了一个视图， 还是生成失败， 是不是不支持视图
missing primary key
视图没主键就不行吗？

**Comment by kevwan** [comment]
> > > @william-best 应该是的，我之前也遇到类似的，官方建议用 datasource 的形式去做自动生成，[#740 (comment)](https://github.com/tal-tech/go-zero/issues/740#issuecomment-851781769)
> > 
> > 
> > 对的，因为要解析对还是比较麻烦，要换库才行，我们本来内网有个web界面，直接让选择哪个库，一键生成然后copy出来的
> 
> 我今天使用datasource的方式， 只不过多了一个视图， 还是生成失败， 是不是不支持视图
> missing primary key
> 视图没主键就不行吗？

主键是需要的

**Comment by william-best** [comment]
> > > > @william-best 应该是的，我之前也遇到类似的，官方建议用 datasource 的形式去做自动生成，[#740 (comment)](https://github.com/tal-tech/go-zero/issues/740#issuecomment-851781769)
> > > 
> > > 
> > > 对的，因为要解析对还是比较麻烦，要换库才行，我们本来内网有个web界面，直接让选择哪个库，一键生成然后copy出来的
> > 
> > 
> > 我今天使用datasource的方式， 只不过多了一个视图， 还是生成失败， 是不是不支持视图
> > missing primary key
> > 视图没主键就不行吗？
> 
> 主键是需要的

视图不是没主键吗？
还有一个问题， 不支持联合主键吗？

**Comment by kevwan** [comment]
> > > > > @william-best 应该是的，我之前也遇到类似的，官方建议用 datasource 的形式去做自动生成，[#740 (comment)](https://github.com/tal-tech/go-zero/issues/740#issuecomment-851781769)
> > > > 
> > > > 
> > > > 对的，因为要解析对还是比较麻烦，要换库才行，我们本来内网有个web界面，直接让选择哪个库，一键生成然后copy出来的
> > > 
> > > 
> > > 我今天使用datasource的方式， 只不过多了一个视图， 还是生成失败， 是不是不支持视图
> > > missing primary key
> > > 视图没主键就不行吗？
> > 
> > 
> > 主键是需要的
> 
> 视图不是没主键吗？
> 还有一个问题， 不支持联合主键吗？

联合主键不支持的

**Comment by bendh1** [comment]
建议还是把sql执行到数据库, 用datasource的方式跑model这样问题少一点

**Comment by william-best** [comment]
视图的代码， 分页的代码 等都是手撸的， 最好全是自动生成的， 现在支持的太简单了。
