### ISSUE TITLE
有后台任务项目模板生成吗？

### ISSUE THREAD

**Issue by greyireland** [tal-tech/go-zero#750]
看到文档有一个示例，没有提供源码或者模板生成 
https://go-zero.dev/cn/go-queue.html

**Comment by kevwan** [comment]
https://github.com/tal-tech/go-queue

**Comment by greyireland** [comment]
> https://github.com/tal-tech/go-queue

有项目开发的模板吗？项目结构模板？

**Comment by kevwan** [comment]
这个自己放到一个task目录，跟api和rpc同级。
