### ISSUE TITLE
proto --experimental_allow_proto3_optional was not set

### ISSUE THREAD

**Issue by superlbr** [tal-tech/go-zero#755]
This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set
```
 goctl rpc proto -src user.proto -dir .
```

**Comment by anqiansong** [comment]
@superlbr 
Post your proto3 source code here, please !

**Comment by superlbr** [comment]
```
syntax = "proto3";

package remote;

message Request {
  // 用户名
  optional string username = 1;
  // 用户密码
  string password = 2;
}

message Response {
  // 用户名称
  string name = 1;
  // 用户性别
  string gender = 2;
}

service User {
  // 登录
  rpc Login(Request)returns(Response);
}

```

**Comment by anqiansong** [comment]
@superlbr `Optional` is deprecated in proto3. Some `protoc-gen-go` flags are blocked in goctl. Therefore, to solve this problem, the keyword `optional` can only be removed. For the time being, compatibility is not considered.
