### ISSUE TITLE
后续可以支持Jaeger 链路追踪吗

### ISSUE THREAD

**Issue by smallsha123** [tal-tech/go-zero#757]
后续可以支持Jaeger 链路追踪吗

**Comment by JeffreyBool** [comment]
这个可以搞一下

**Comment by kevwan** [comment]
这个要搞的，其实就是适配一下，现在的做法有很大好处的，缺点就是不能用jaeger或者zipkin等图形化展示

0.1.2.3这种span id可以直观的看出调用深度

**Comment by JeffreyBool** [comment]
> 这个要搞的，其实就是适配一下，现在的做法有很大好处的，缺点就是不能用jaeger或者zipkin等图形化展示
> 
> 0.1.2.3这种span id可以直观的看出调用深度

jaeger 在 ui 图也能看到调用深度，

![image](https://user-images.githubusercontent.com/24415888/122158900-f9bd8080-ce9f-11eb-993e-ef64bd29e7af.png)

![image](https://user-images.githubusercontent.com/24415888/122158955-16f24f00-cea0-11eb-80dd-4d5952bc69cd.png)

**Comment by kevwan** [comment]
> > 这个要搞的，其实就是适配一下，现在的做法有很大好处的，缺点就是不能用jaeger或者zipkin等图形化展示
> > 0.1.2.3这种span id可以直观的看出调用深度
> 
> jaeger 在 ui 图也能看到调用深度，
> 
> ![image](https://user-images.githubusercontent.com/24415888/122158900-f9bd8080-ce9f-11eb-993e-ef64bd29e7af.png)
> 
> ![image](https://user-images.githubusercontent.com/24415888/122158955-16f24f00-cea0-11eb-80dd-4d5952bc69cd.png)

我说的是能从框架层面检测深度并加以限制

**Comment by kevwan** [comment]
已支持
