### ISSUE TITLE
goctl 报错 open cpuacct.usage_percpu: no such file or directory

### ISSUE THREAD

**Issue by feitian124** [tal-tech/go-zero#774]
goctl 升级到 `1.1.6` 后， 运行时会报如下一个错误， 升级到 `1.1.8`后依旧。
```sh
± |master ✓| → goctl -v
2021/06/21 14:43:40 {"@timestamp":"2021-06-21T14:43:40.307+08","level":"error","content":"cpu_linux.go:29 open cpuacct.usage_percpu: no such file or directory"}
goctl version 1.1.8 linux/amd64

```

该问题似乎不影响使用， 但影响心情， 也反映一些兼容性等潜在问题， 故记录于此。
我的 操作系统版本: `Manjaro 21.0.7 Ornara kde`
我的go 版本: `go version go1.16.4 linux/amd64`

在群内反应后， 有人说查看一些 cpuacct 信息看看:
>
   打印一下 os.Getpid()
   cat /proc/{os.Getpid}/cgroup

```sh
0::/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole-e04738a143fe4fb89fd831e469647602.scope
```

没有cpuacct信息

**Comment by anqiansong** [comment]
@feitian124 这个是操作系统层的问题，跟`goctl`没有关系，这个可以自行排查一下。
