### ISSUE TITLE
stat.DisableLog() 无效

### ISSUE THREAD

**Issue by hubyao** [tal-tech/go-zero#780]
在代码里添加stat.DisableLog(),控制台照常输出

**Comment by kevwan** [comment]
输出内容是啥？

**Comment by hubyao** [comment]
![image](https://user-images.githubusercontent.com/32606145/123026843-6dffa300-d40f-11eb-9c08-fb7c2c768908.png)

**Comment by hubyao** [comment]
> 输出内容是啥？

![image](https://user-images.githubusercontent.com/32606145/123026864-7526b100-d40f-11eb-9dac-d3ad15b6ed3d.png)

**Comment by kevwan** [comment]
要禁掉这个可以用 `load.Disable()` 禁用降载

**Comment by hubyao** [comment]
这个我也用了,你看stat.DisableLog()下面一行代码

**Comment by hubyao** [comment]
> 要禁掉这个可以用 `load.Disable()` 禁用降载

这个我也用了,你看stat.DisableLog()下面一行代码

**Comment by hubyao** [comment]
> > 要禁掉这个可以用 `load.Disable()` 禁用降载
> 
> 这个我也用了,你看stat.DisableLog()下面一行代码

我是从老版本直接升级的,会不会有影响

**Comment by kevwan** [comment]
这个输出其实挺有帮助的，不知道为啥要去掉

**Comment by hubyao** [comment]
> 这个输出其实挺有帮助的，不知道为啥要去掉

比较影响看正常的输出或者调试日志

**Comment by kevwan** [comment]
一分钟输出一次的
