### ISSUE TITLE
[建议] 请求日志content的字段json化

### ISSUE THREAD

**Issue by hubyao** [tal-tech/go-zero#781]
![image](https://user-images.githubusercontent.com/32606145/123028887-bb314400-d412-11eb-86d9-bbbb63c54c4f.png)
可以换成 
```
{
	"content": {
		"url": "/system/get_current_time",
		"header": {},
		"response":"",
	}
}
```
没有完全列举,就是类似这种结构.

**Comment by kevwan** [comment]
已修改，见master代码，欢迎测试
