### ISSUE TITLE
请问是否支持自定义接口级别的serverSlowThreshold

### ISSUE THREAD

**Issue by spencer404** [tal-tech/go-zero#785]
服务端有大量slow日志：
> "level":"slow","duration":"507.3ms","content":"[RPC] slowcall...

某些接口的响应时间确实会超过500ms，但在不超过1000ms时在业务和性能上都属正常。
请问能否针对接口配置serverSlowThreshold，未配置则默认500ms。

**Comment by kevwan** [comment]
我还是觉得你应该优化服务，500ms已经很慢了。
