### ISSUE TITLE
How go-zero deal with http DELETE request with form params or  jsons params?

### ISSUE THREAD

**Issue by JiangHanChao** [tal-tech/go-zero#787]
I defined a delete api with params like this:

> delete /api/v1/something (Request) returns(Response)
> type Request {
>       mode string \`form:mode\`
> }

and I test this api with:

> curl -X DELETE http://127.0.0.1/api/v1/something  -d 'mode="xxx"'

then it reports error in server log:

> 2021xxxxxtime warning [server] {"content":"[7483] [HTTP] 200 - /api/v1/something - 127.0.0.1: - curl/7.62.0 - slowcall(500.4ms)","trace":"5d2ea2a5cbb447e4","span":"0"}
> 2021xxxxxtime info [server] {"content":"[7483] 200 - /api/v1/something - 127.0.0.1: - curl/7.62.0 - 500.4ms","trace":"5d2ea2a5cbb447e4","span":"0"}

and curl call  returns a error

what's wrong with it? 

I guess it should be wrong in http delete method because when I use `path` params in same api, it goes!

go version go1.15.2 linux/amd64

**Comment by miaogaolin** [comment]
api file is wrong！Missing double quotes
correct:
```go
type Request {
mode string `form:"mode"`
}
```

**Comment by JiangHanChao** [comment]
@miaogaolin 
I apologize for my wrong copying code, but in my reality project this is checking pass with goctl tools:
`goctl api go -api project.api -dir .`
and auto-generated code is correctly using in project.

Maybe there are other reason for this question, because when I change to use post method in this api, it works with params.

**Comment by JiangHanChao** [comment]
Put another way, did go-zero support DELETE method with body params?

**Comment by miaogaolin** [comment]
> Put another way, did go-zero support DELETE method with body params?

Yes.It did

**Comment by miaogaolin** [comment]
> Put another way, did go-zero support DELETE method with body params?

![image](https://user-images.githubusercontent.com/57740293/125427195-958eabf7-d10a-4b25-b071-c6a42d03cafc.png)

**Comment by JiangHanChao** [comment]
> > Put another way, did go-zero support DELETE method with body params?
> 
> ![image](https://user-images.githubusercontent.com/57740293/125427195-958eabf7-d10a-4b25-b071-c6a42d03cafc.png)

Thanks, I get what's wrong in my method, in curl docs it says:
```
-d, --data <data>
     (HTTP MQTT) Sends the specified data in a POST request to the HTTP server, in the same way that a browser does 
     when a user has filled in an HTML form and presses the submit button. This will cause curl to pass the data to the server 
     using the content-type application/x-www-form-urlencoded. Compare to -F, --form.
```
Thanks a lot.
