### ISSUE TITLE
为goctl 添加postgresql 生成支持？

### ISSUE THREAD

**Issue by yangkequn** [tal-tech/go-zero#793]
postgresql 由于诸多无法拒绝的新特性，现在每年都在快速普及，pg 成长惊人。特别是在美国市场，pg已经得到了一半的份额。
数据库的选型是一种很强硬的约束，往往没得选。
https://hellogithub.com/report/db-engines/

强烈期望添加从数据库生成model 的支持。如果没有这种支持，go-zero 各种缓存等好处就不用上。武功废了一半，让人难受。

总之，go-zero 是心头肉，POSGRESQL 也是心头肉。期待俩好成一好，让我少点作为开发人员的一根筋的痛苦纠结

**Comment by 851091009** [comment]
请问现在有进度吗？什么时候可以完成支持？

**Comment by zf8848** [comment]
postgresql 的 gis 插件还是很好用的。不知道 什么时候 支持 postgresql?

**Comment by Coder-stars** [comment]
PG还是很赞的，感觉很有必要支持。

**Comment by anqiansong** [comment]
#842 已修复

**Comment by kurimi1** [comment]
goctl pg 生成无法使用
![image](https://user-images.githubusercontent.com/33993460/127476498-72f4f52b-3b95-4d23-aa33-03a223bb7cda.png)
存在2个问题
1. url后必须加“=”？
2. 用户默认root无法更改
![image](https://user-images.githubusercontent.com/33993460/127477093-966da708-8d1d-4e21-922c-0ed5ed79bcc8.png)
![image](https://user-images.githubusercontent.com/33993460/127476967-559f333d-b804-4e56-8fd1-b599bf5f14a7.png)

**Comment by kurimi1** [comment]
关于pg链接的问题已解决，url格式不正确。
url在pg官方库解析有两种方式：
1.
`host=%s port=%s dbname=%s user=%s password=%s sslmode=disable`
2.
`postgres://yourname:yourpassword@127.0.0.1:5432/database?sslmode=disable`
现存在生成代码不支持pg数据格式问题：
![image](https://user-images.githubusercontent.com/33993460/127594064-85e0ce04-b8bb-449b-82bd-505bf5fe8b54.png)

**Comment by yangkequn** [comment]
just copy the code

model pg datasource -url="postgres://yourname:yourpassword@127.0.0.1.com:5432/database?sslmode=disable" -table="table" -c -dir modeldir

**Comment by ruikc** [comment]
> just copy the code
> 
> goctl model pg datasource -url="postgres://yourname:[yourpassword@127.0.0.1.com](mailto:yourpassword@127.0.0.1.com):5432/database?sslmode=disable" -table="table" -c -dir modeldir

command "goctl model pg datasource -url="postgres://zhiyuan:zhiyuan@127.0.0.1:5432/123d_cc?sslmodel=disable" -table="user" -c -dir ./"

but error 

goctl error: pq: SSL is not enabled on the server
