### ISSUE TITLE
goctl api 生成包含List代码的Bug

### ISSUE THREAD

**Issue by yangkequn** [tal-tech/go-zero#795]
type (
	readCorpusRet {
		Id       int64  `json:"id"`
)
type (
	readCorpusSetRsb {
		List []readCorpusRet `json:"list"`
	}
)

生成的代码

type ReadCorpusRet struct {
	Id       int64  `json:"id"`
}
type ReadCorpusSetRsb struct {
	List []readCorpusRet `json:"list"`
}

其中 List []readCorpusRet  的 readCorpusRet 应当为大写才是正确的

**Comment by skykiss** [comment]
为什么定义的时候没有大写吗？定义的时候大写应该生成的就是大写的
