### ISSUE TITLE
zero升级到最新版本，etcd注册出现问题

### ISSUE THREAD

**Issue by xhochipe** [tal-tech/go-zero#803]
我etcd对外暴露 49175,49178,49179端口
启动项目出现如下错误

{"level":"warn","ts":"2021-07-02T15:11:12.531+0800","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00034c000/#initially=[49.232.203.57:49175;49.232.203.57:49178;49.232.203.57:49179]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:2379: connectex: No connection could be made because the target machine actively refused it.\""}

**Comment by Jackson8888** [comment]
问一下问题是怎么解决的

**Comment by QuaidChen** [comment]
同问
