### ISSUE TITLE
请问跨数据库联合查询怎么实现 ?

### ISSUE THREAD

**Issue by 851091009** [tal-tech/go-zero#808]

**Comment by zyu** [comment]
我现在准备用zorm替换gozero里面的xorm 数据库什么的就不是事了，老哥的我写完给测测呗

**Comment by kevwan** [comment]
go-zero的orm是为了缓存和代码自动生成，如果不需要，自己替换即可。

**Comment by 851091009** [comment]
> 我现在准备用zorm替换gozero里面的xorm 数据库什么的就不是事了，老哥的我写完给测测呗

我用 gorm 比较多一点，zorm 还没用过，你的意思是需要我帮你测试吗？如果是话，到时候请在这里联系我

**Comment by 851091009** [comment]
> 我现在准备用zorm替换gozero里面的xorm 数据库什么的就不是事了，老哥的我写完给测测呗

我用 gorm 比较多一点，zorm 还没用过，你的意思是需要我帮你测试吗？如果是话，到时候请在这里联系我

**Comment by 851091009** [comment]
> go-zero的orm是为了缓存和代码自动生成，如果不需要，自己替换即可。

嗯，项目数据库是 postgreSQL, 我现在使用的 gorm。

还有个疑问：

做微服务后，每个拆分的微服务对应一个数据库实例，有可能部署在不同的服务器上。下面的情况请问怎么实现。
举例：
客户微服务订单微服务，数据库不在一个服务器上。当获取客户的列表，同时这些客户需要获取到他的全部订单列表。在微服务中，这些客户怎么去获取他的全部订单。

**Comment by feihua** [comment]
用到了分库分表，可以试下Sharding-Proxy和mycat这些中间件，看下能解决你的问题不，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月9日(星期五) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [tal-tech/go-zero] 请问跨数据库联合查询怎么实现 ? (#808)





  
go-zero的orm是为了缓存和代码自动生成，如果不需要，自己替换即可。
  
嗯，项目数据库是 postgreSQL, 我现在使用的 gorm。
 
还有个疑问：
 
做微服务后，每个拆分的微服务对应一个数据库实例，有可能部署在不同的服务器上。下面的情况请问怎么实现。
 举例：
 客户微服务订单微服务，数据库不在一个服务器上。当获取客户的列表，同时这些客户需要获取到他的全部订单列表。在微服务中，这些客户怎么去获取他的全部订单。

**Comment by 851091009** [comment]
> 用到了分库分表，可以试下Sharding-Proxy和mycat这些中间件，看下能解决你的问题不，
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年7月9日(星期五) 下午3:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [tal-tech/go-zero] 请问跨数据库联合查询怎么实现 ? (#808) go-zero的orm是为了缓存和代码自动生成，如果不需要，自己替换即可。 嗯，项目数据库是 postgreSQL, 我现在使用的 gorm。 还有个疑问： 做微服务后，每个拆分的微服务对应一个数据库实例，有可能部署在不同的服务器上。下面的情况请问怎么实现。 举例： 客户微服务订单微服务，数据库不在一个服务器上。当获取客户的列表，同时这些客户需要获取到他的全部订单列表。在微服务中，这些客户怎么去获取他的全部订单。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

非常感谢！！！！！！！！！！！！！！！！！！！！！！！
