### ISSUE TITLE
ToCamel方法是不是应该对一些特殊名称做处理

### ISSUE THREAD

**Issue by szpnygo** [tal-tech/go-zero#809]
https://github.com/mgechev/revive/blob/master/lint/utils.go#L89
https://github.com/golang/lint/blob/master/lint.go#L770

参照commonInitialisms里的单词
比如
id => ID
ip => IP

**Comment by anqiansong** [comment]
@szpnygo 感谢，我去做一下处理。

**Comment by anqiansong** [comment]
@szpnygo 这个问题我考虑了一下，要将部分关键词如 `id`，`ip`等转换正确，修复后新版本生成会造成线上已有服务出现编译错误，导致大面积不兼容，因此这一块目前不考虑去补丁了。感谢你的反馈！

**Comment by szpnygo** [comment]
@anqiansong 我也想到了，，所以我只是本地自己把这一块改了下自己用。
