### ISSUE TITLE
希望加载SVC依赖时能对外部依赖做验证

### ISSUE THREAD

**Issue by kurimi1** [tal-tech/go-zero#812]
main函数中加载依赖代码：
`ctx := svc.NewServiceContext(c)`
我的数据库和redis地址是错误的，数据库会在调用crud函数时报错，但redis没有任何报错！

**Comment by kurimi1** [comment]
redis会在查询时报错，但在加载svc时就验证外部依赖是不是更好？

**Comment by leafmirror** [comment]
> redis会在查询时报错，但在加载svc时就验证外部依赖是不是更好？

这样启动的时候 检测的就有点多了 ，启动速度会慢
