### ISSUE TITLE
goctl api 中，route是否支持any或定义多个请求方式？

### ISSUE THREAD

**Issue by Thunural** [tal-tech/go-zero#817]
例如
@handler WechatInterface
any /wechat/index () returns()

**Comment by Thunural** [comment]
在api层对接微信时微信会发起一个get请求，在用户发送信息时微信会post到此地址，每次如果改动了api文件在执行goctl api生成的时候会覆盖掉route的配置。有没有好的解决方案？

**Comment by AkatsukiAkira** [comment]
hi,这个问题解决了吗？

**Comment by Flipped199** [comment]
同问，这个问题解决了吗

**Comment by coverthesea** [comment]
我研究了一下，用gin的路由解决
https://github.com/zeromicro/zero-contrib/blob/main/router/gin/README.md

这个东西，复制出去自己改一份，处理一下ANY的Method，就能实现了
