### ISSUE TITLE
[BUG反馈]在redis-cluster模式下，删除多个缓存key报错CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by ldmid666** [tal-tech/go-zero#820]
redis cluster模式集群使用go-zero 生成的model代码，执行update函数时候（函数包含两个唯一索引缓存），经常出现的”CROSSSLOT Keys in request don't hash to the same slot “报错。
貌似是cluster模式下同时删除两个key，而这两个key不在一个节点槽会出现这个问题。

![image](https://user-images.githubusercontent.com/49946804/125765595-4e23b295-40ea-4b6f-8e03-a908b775354e.png)

![image](https://user-images.githubusercontent.com/49946804/125765416-3519d081-1cbb-447e-9b87-e851c8a19282.png)

这个问题是不是包装的go-redis库自身潜在的bug？

**Comment by ldmid666** [comment]
最新版这个bug有修复吗？

**Comment by ldmid666** [comment]
这个问题，看最新发布版本中依然存在，这个bug为啥还不修复呢

**Comment by kevwan** [comment]
> 这个问题，看最新发布版本中依然存在，这个bug为啥还不修复呢

生成代码里每个key删除一次才行

**Comment by ldmid666** [comment]
> > 这个问题，看最新发布版本中依然存在，这个bug为啥还不修复呢
> 
> 生成代码里每个key删除一次才行

是的，当初有在群里反馈，说会修复的。
