### ISSUE TITLE
goctl rpc proto 生成代码文件的时候报异常

### ISSUE THREAD

**Issue by xhochipe** [tal-tech/go-zero#825]
``` goctl rpc proto -src .\b.proto -dir .  -style go_zero ```

目录:
  ``` rpc:
          b.proto
          common.proto
      
    common.proto:
            syntax = "proto3";
            package common;
            option go_package ="./src";
             message RetResp {
                     bytes Data = 1;
              }
             message Empty {}
     b.proto:
           syntax = "proto3";
           import "common.proto";
          import "google/protobuf/empty.proto";
           package b;

           option go_package ="./src";

           service B{
                rpc Hello(common.Empty) returns(common.RetResp);
                rpc Api(google.protobuf.Empty) returns(RetResp);
           }
```

在上面引入google中的Empty 和自己common.proto中定义的message ,goctl rpc proto 生成代码都报错：request type must defined in b.proto

protoc version: libprotoc 3.17.3
goctl :goctl.exe version 1.1.6 windows/amd64

**Comment by anqiansong** [comment]
@xhochipe 这个我在文档中有说明，request和response不支持外部的message。

**Comment by arthur-jx** [comment]
> @xhochipe 这个我在文档中有说明，request和response不支持外部的message。

在一个项目中，很多结构本来是可以共用的，不支持外部的message, 就需要在各个.proto中重复定义，这会给维护带来了很多不方便和不一致呀？

**Comment by gghtrt520** [comment]
期望加强，不然proto文件中定义的message就重复太多了

**Comment by Danny5487401** [comment]
哪时候可以支持外部的message @anqiansong

**Comment by wuyazi** [comment]
最近也遇到了，希望能支持下。
看了下代码，支持的话，除了影响 logic 和 client 的生成，还影响别的不
@anqiansong

**Comment by Visforest** [comment]
如果不支持引入外部 protobuf 的话，protobuf 本身的功能就会大打折扣，造成很多代码冗余，go-zero 就显得很鸡肋了

**Comment by dylanzan** [comment]
这个到最后怎么解决的？遇到了同样的问题

**Comment by fucktx** [comment]
> 这个到最后怎么解决的？遇到了同样的问题

jzero

**Comment by dylanzan** [comment]
> > 这个到最后怎么解决的？遇到了同样的问题
> 
> jzero

我的解决方法是传入了一个空结构体
