### ISSUE TITLE
goctl生成缓存代码在某些情况下面会冲突

### ISSUE THREAD

**Issue by feixiao** [tal-tech/go-zero#830]
# 自动生成代码使用下面的前缀
cacheUserIdPrefix     = "cache:user:id:"
cacheUserUserIdPrefix = "cache:user:userId:"

当不同数据库存在相同名字的表的时候缓存会冲突，建议在添加数据库名字来区分

**Comment by anqiansong** [comment]
> # 自动生成代码使用下面的前缀
> cacheUserIdPrefix = "cache:user🆔"
> cacheUserUserIdPrefix = "cache:user:userId:"
> 
> 当不同数据库存在相同名字的表的时候缓存会冲突，建议在添加数据库名字来区分

这个问题我考虑一下。
