### ISSUE TITLE
template 自定义模板全局的么

### ISSUE THREAD

**Issue by brady-wang** [tal-tech/go-zero#831]
goctl template init 之后一个项目是可以根据自定义模板生成了
但是另外的项目想再用就得 goctl template clean  
如果多个项目岂不是切换很麻烦

**Comment by zhangyangchen** [comment]
是不是可以把模版可以放到代码项目里，或者自定义引用模版路径 @kevwan

**Comment by kevwan** [comment]
增加个指定模板路径参数就好了

**Comment by anqiansong** [comment]
已纳入计划
