### ISSUE TITLE
goctl api new greet命令报错

### ISSUE THREAD

**Issue by ymj4023** [tal-tech/go-zero#833]
无法完整新建项目,从头重试过多遍依然不行，在其他win10电脑上未出现相同问题。
![1](https://user-images.githubusercontent.com/44188893/126345847-bf4dd8c7-49de-4892-946b-8ad2d2f52a0e.png)
GO111MODULE,GOPATH,GOPROXY环境已配置
goctl,protoc-gen-go,protoc.exe等已配置
平台:win10专业版
版本号:1903
操作系统版本:18362.1256

**Comment by ymj4023** [comment]
Release v1.1.8

**Comment by anqiansong** [comment]
@ymj4023 你这个乱码考虑先讲你的终端编码改成`utf-8`再试一下，好明确知道错误日志。

**Comment by ymj4023** [comment]
已解决。去掉环境变量中的GOPATH跟GOROOT可以了。
