### ISSUE TITLE
v1.1.8 Bug 反馈

### ISSUE THREAD

**Issue by NeroCho** [tal-tech/go-zero#834]
1.1.8下，go mod tidy 会导致 replace google.golang.org/grpc => google.golang.org/grpc v1.29.1 失效，可能因为1.1.8的 mod中引用了grpc@v1.38？
然后报错（p2cPicker does not implement balancer.Picker (wrong type for Pick method)）

**Comment by NeroCho** [comment]
![image](https://user-images.githubusercontent.com/7479275/126419185-1f8110ab-3187-4003-8c8c-40f3847fe999.png)
![image](https://user-images.githubusercontent.com/7479275/126419216-5c0ed718-73d0-4f91-9f3d-8ab0033fe67d.png)

如图，运行go mod tidy ，然后grpc 版本就会变成1.38。。。 然后又不支持。。。

**Comment by anqiansong** [comment]
> replace google.golang.org/grpc => google.golang.org/grpc v1.29.1

升级[1.1.8](https://github.com/tal-tech/go-zero/releases/tag/v1.1.8)后不用`replace google.golang.org/grpc => google.golang.org/grpc v1.29.1`了

**Comment by NeroCho** [comment]
> > replace google.golang.org/grpc => google.golang.org/grpc v1.29.1
> 
> 升级[1.1.8](https://github.com/tal-tech/go-zero/releases/tag/v1.1.8)后不用`replace google.golang.org/grpc => google.golang.org/grpc v1.29.1`了

我刚才新建了个项目发现确实没问题。。。
