### ISSUE TITLE
goctl model 不支持 mysql blob 类型 ?

### ISSUE THREAD

**Issue by soar4** [tal-tech/go-zero#836]
$ cat user.sql
CREATE TABLE `user` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `number` varchar(255) NOT NULL DEFAULT '' COMMENT '学号',
    `gif` BLOB NOT NULL COMMENT 'picture',
    `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `number_unique` (`number`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ;

尝试根据 sql 语句生成代码,提示错误:
$ goctl model mysql ddl --src user.sql -c
error: unexpected database type: blob

**Comment by anqiansong** [comment]
可以支持`blob`到`string`，目前没有开放。
