### ISSUE TITLE
RPC调用建议

### ISSUE THREAD

**Issue by langbin522** [tal-tech/go-zero#837]
用了几天zero了。感觉都不错。只是在RPC调用这个不够灵活。因为有很多时候RPC服务会临时上线。临时下线。如果突然增加多个RCP的话还需要在API绑定修改增加相应RPC服务。这与自动发现自动注册好像有点违背了。如果改成通过调用指定相关的RPC那就方便很多（比如通name或key字符串来调用相应的RPC）。网关也不需要修改了。业务只需要上线RPC，然后网关那边就能调用了。而不是像现在如果有新上RPC，需要改config配置。

**Comment by kevwan** [comment]
类似FaaS了吧？

**Comment by langbin522** [comment]
> 
> 
> 类似FaaS了吧？

也不算吧。如果把RPC这块做成即插即用，这样就比较灵活了

**Comment by kevwan** [comment]
> > 类似FaaS了吧？
> 
> 也不算吧。如果把RPC这块做成即插即用，这样就比较灵活了

这个不太赞同哈，因为微服务的根基是为了稳定，灵活需要做一定的让步。

**Comment by langbin522** [comment]
> 
> 
> > > 类似FaaS了吧？
> > 
> > 
> > 也不算吧。如果把RPC这块做成即插即用，这样就比较灵活了
> 
> 这个不太赞同哈，因为微服务的根基是为了稳定，灵活需要做一定的让步。

比如像 kratos 的调用他们是这样做的
`conn, err := grpc.DialInsecure(    
      context.Background(),    
      grpc.WithEndpoint("discovery:///helloworld"),  //可能通过发现来调用相应的RPC服务
      grpc.WithDiscovery(r),
)`

**Comment by kevwan** [comment]
> > 
> 
> > 
> 
> > > > 类似FaaS了吧？
> 
> > > 
> 
> > > 
> 
> > > 也不算吧。如果把RPC这块做成即插即用，这样就比较灵活了
> 
> > 
> 
> > 这个不太赞同哈，因为微服务的根基是为了稳定，灵活需要做一定的让步。
> 
> 
> 
> 比如像 kratos 的调用他们是这样做的
> 
> `conn, err := grpc.DialInsecure(    
> 
>       context.Background(),    
> 
>       grpc.WithEndpoint("discovery:///helloworld"),  //可能通过发现来调用相应的RPC服务
> 
>       grpc.WithDiscovery(r),
> 
> )`

这个就是go-zero的discov模式吧
