### ISSUE TITLE
一个rpc里调用另外多个rpc 时 使用l.ctx 会报错 context deadline exceeded,如何解决

### ISSUE THREAD

**Issue by GnezIew** [tal-tech/go-zero#841]

**Comment by nickzhuyb** [comment]
l.ctx => context.Background()

**Comment by kevwan** [comment]
执行时间过长吧，贴代码哈

**Comment by zhoushuguang** [comment]
> l.ctx => context.Background()

这样不行的，信息没法传递了

**Comment by liangjiefei** [comment]
解决了吗这个问题

**Comment by kevwan** [comment]
> 解决了吗这个问题

这个是使用问题吧

**Comment by kevwan** [comment]
级联超时传递使用问题，先关了

**Comment by GnezIew** [comment]
解决了 直接
 `ctx,cancel := context.WithCancel(context.Background())
defer cancel()`

**Comment by kevwan** [comment]
> 解决了 直接
> `ctx,cancel := context.WithCancel(context.Background()) defer cancel()`

你这是放弃了前面的超时设置

**Comment by GnezIew** [comment]
> > 解决了 直接
> > `ctx,cancel := context.WithCancel(context.Background()) defer cancel()`
> 
> 你这是放弃了前面的超时设置

比如订单rpc 调用 用户信息rpc,如果我用 l.ctx就会出现超时，所以就用了只这个方法

**Comment by GnezIew** [comment]
> > > 解决了 直接
> > > `ctx,cancel := context.WithCancel(context.Background()) defer cancel()`
> > 
> > 
> > 你这是放弃了前面的超时设置
> 
> 比如订单rpc 调用 用户信息rpc,如果我用 l.ctx就会出现超时，所以就用了只这个方法

请问下大佬，那应该如何保证不放弃的超时设置的前提下，还能成功调用其他的rpc呢？
