### ISSUE TITLE
是否考虑加个手工连RPC服务的方法呢？

### ISSUE THREAD

**Issue by langbin522** [tal-tech/go-zero#851]
是否考虑加个手动连RPC的方法吗？
有时候要用到的RPC不是一直在线的。能否加个手工连RPC服务的方法。这样我们可以在需要的地方手工去连接RPC服务

**Comment by kevwan** [comment]
grpcurl?

**Comment by langbin522** [comment]
> 
> 
> grpcurl?

我的意思是，在API业务逻辑里面再去连接grpc服务。能否提供一个 连接方法。而不是在config.yaml里配置的grpc。

**Comment by kevwan** [comment]
MustNewClient，然后传进去一个配置对象就好了
