### ISSUE TITLE
解决注册路由的时候，不能同时设置WithNotAllowedHandler和WithNotFoundHandler

### ISSUE THREAD

**Issue by lifang218c** [tal-tech/go-zero#852]
需要把所有的请求都写日志，包括404和204，在用到框架提供的方法的时候，发现不能同时生效，使用方式如下：
![image](https://user-images.githubusercontent.com/3444386/127437314-b9585a23-bbe8-400d-a9f1-fc0a6ddddf29.png)
然后看了框架代码，发现这两个方法不是公用一个patrouter，所以提了一个pr

**Comment by kevwan** [comment]
Duplicate of #875
