### ISSUE TITLE
api文件使用import 时生成代码出错

### ISSUE THREAD

**Issue by yangjiahao106** [tal-tech/go-zero#854]
api文件使用import 时导入的类型放入数组中会出错，比如

```go
import "warehouse.api"

type Filters {
	WareHouses []warehouse.WareHouse `json:"wareHouses"` 
}
```
错误 ：
error: objects.api line 16:34  extraneous input '`json:"wareHouses"`' expecting {'}', '*', ID}

不用作数组时是正常的，比如：
```go
import "warehouse.api"
type Filters {
	WareHouses warehouse.WareHouse `json:"wareHouses"` // 仓库信息
}
```

**Comment by anqiansong** [comment]
@yangjiahao106 `WareHouse `结构体是 import 自 `warehouse.api` 对吧，这个正确写法是
```
WareHouses []WareHouse `json:"wareHouses"` 
```
目前api文件没有package的概念

**Comment by yangjiahao106** [comment]
> @yangjiahao106 `WareHouse `结构体是 import 自 `warehouse.api` 对吧，这个正确写法是
> 
> ```
> WareHouses []WareHouse `json:"wareHouses"` 
> ```
> 
> 目前api文件没有package的概念
---
@anqiansong 
感谢回复。这样是可以正常使用，就是在goland 编辑器中会提示一个无法解析的错误，看着比较难受。（已经安装了goctl 插件）

**Comment by anqiansong** [comment]
这个目前有时间再考虑优化，不影响使用。proto也是这样的
