### ISSUE TITLE
最新的go-zero版本，依赖没有修改，etcd部署在k8s报warn

### ISSUE THREAD

**Issue by Jackson8888** [tal-tech/go-zero#858]
{"level":"warn","ts":"2021-07-30T17:11:40.473+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003d7340/#initially=[etcd-svc:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused\""}

**Comment by kevwan** [comment]
dial 0.0.0.0:2379是你配置错误哈，0.0.0.0不能用来dial的。
