### ISSUE TITLE
建议 goctl 支持直接根据golang的接口结构体生成proto文件和sql文件，可以节省大量手写proto和sql的时间

### ISSUE THREAD

**Issue by yemuapp** [tal-tech/go-zero#859]
用go zero一段时间了，最近将以前的几个小项目用go zero重构跑了一下，重构完毕后发现大量时间都是花费在手写proto文件上。

后面为了偷懒直接用工具一键生成了，建议goctl 加入这个功能，真的可以节省大量时间。

假设一个场景，需要对用户数据表进行增删改查，先写好UserModel结构体，然后直接用gorm生成数据表，接下来需要些对user表进行增删改查的rpc，到了这一步之后需要先定义 proto 文件，这部分都只能一条条手写，如果 goctl 可以增加一个命令，对定义的model 一键生成的话那就会节省大量时间。

比如我定义的接口结构体如下 
```golang
package user

type User interface {
	SearchUser(request Request) Response // 搜索用户
	CreateUser(request Request) Response // 创建用户
	UpdateUser(request Request) Response // 更新用户
	DeleteUser(request Request) Response // 删除用户
}

type Request struct {
	Name string
}
type Response struct {
	Result string
}
```

使用工具一键生成proto的文件内容如下

```proto
syntax = "proto3";
package proto;

service User {
    rpc SearchUser (Request) returns (Response) {} // 搜索用户
    rpc CreateUser (Request) returns (Response) {} // 创建用户
    rpc UpdateUser (Request) returns (Response) {} // 更新用户
    rpc DeleteUser (Request) returns (Response) {} // 删除用户
}

message Request {
    string Name = 1; 
}

message Response {
    string Result = 1; 
}
```

后续需要增加接口或者字段也只需要修改golang的接口结构体就行，改好后一键生成对应的proto文件和sql文件，proto文件用于rpc，sql文件用于goctl生成model，省去手写sql的麻烦，实际上更建议类似gorm的做法直接根据定义的struct生成数据表，而不是根据数据表去生成model

参考工具包 go2proto，gorm2sql，gorm等

**Comment by MaxToby** [comment]
可以通过模版的方式解决。  goctl template init

**Comment by anqiansong** [comment]
在goctl中我目前不会实现这样的生成功能，model成代码生成的结构体本身和rpc就没有直接关联。

**Comment by kevwan** [comment]
设计选择，不会这么支持哈
