### ISSUE TITLE
关于服务监控问题请教

### ISSUE THREAD

**Issue by xhochipe** [tal-tech/go-zero#866]
我部署了prometheus  端口是9091
然后我在不同的服务中的.yaml中加了如下配置
``` Prometheus:
   Host: 127.0.0.1
   Port: 9091
   Path: /metrics
```

运行第一个服务没问题,运行第一个会提示
{"@timestamp":"2021-08-03T14:12:43.286+08","level":"error","content":"agent.go:37 listen tcp 127.0.0.1:9091: bind: address already in use"}

**Comment by feihua** [comment]
不同服务的要不一样端口，不能都 用9091，配置不同的target

**Comment by feihua** [comment]
例如：
服务A
Prometheus:
  Host: 127.0.0.1
  Port: 8180
  Path: /metrics
服务B
Prometheus:
  Host: 127.0.0.1
  Port: 8181
  Path: /metrics
服务C
Prometheus:
  Host: 127.0.0.1
  Port: 8182
  Path: /metrics
   
prometheus.yml配置

global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'file_ds'
    file_sd_configs:
    - files:
      - targets.json
  - job_name: '服务A'
    static_configs:
    - targets: ['10.168.96.23:8180']
  - job_name: '服务B'
    static_configs:
    - targets: ['10.168.96.23:8181']
  - job_name: '服务C'
    static_configs:
    - targets: ['10.168.96.23:8182']
	
注意：上面的10.168.96.23修改为你自己启动服务机器的ip（不是部署prometheus的机器的ip）

**Comment by xhochipe** [comment]
ok 谢谢
