### ISSUE TITLE
open cpuacct.usage_percpu: no such file or directory   

### ISSUE THREAD

**Issue by chengbao1** [tal-tech/go-zero#870]
在CentOS release 6.10 (Final)系统下部署，启动服务时会出现cpu_linux.go:29 open cpuacct.usage_percpu: no such file or directory这个错误

2021/08/04 11:20:04 {"@timestamp":"2021-08-04T11:20:04.300+08","level":"error","content":"cpu_linux.go:29 open cpuacct.usage_percpu: no such file or directory"}

**Comment by kevwan** [comment]
补充下linux内核版本号哈

**Comment by chengbao1** [comment]
linux内核版本号：2.6.32-754.2.1.el6.x86_64

**Comment by kevwan** [comment]
这个版本的内核是2009年发布的，2016年官方已经不支持了，而且docker最低支持到3.10，所以这个就不去兼容了哈

而且，这个报错没关系的，只是不能做cpu统计，不会有自适应降载，服务还是可以正常跑的。
