### ISSUE TITLE
官方文档中没有看到amqp的相关介绍，官方是否有这些组件的支持？

### ISSUE THREAD

**Issue by jettjia** [tal-tech/go-zero#879]
在文档中没有搜索到amqp的相关介绍，不知道官方会不会支持这个，项目中使用三方的队列很常见

**Comment by MaxToby** [comment]
zero框架暂时没有封装。队列可以看下[go-queue](https://github.com/tal-tech/go-queue)这个项目

**Comment by kevwan** [comment]
队列不属于go-zero的功能，你可以用go-zero里的core/queue去实现amqp。
