### ISSUE TITLE
api中相同handler的问题

### ISSUE THREAD

**Issue by windpiaoxue** [tal-tech/go-zero#913]
我想在多个api接口中共用一个handler，这几个接口间的middleware不同。用goctl生成时会报错，有其他方案可以做到吗？

**Comment by MaxToby** [comment]
可以手写路由实现
```
engine.AddRoute(rest.Route{
		Method:  http.MethodGet,
		Path:    "/",
		Handler: handleGet,
})
```

**Comment by kevwan** [comment]
> 我想在多个api接口中共用一个handler，这几个接口间的middleware不同。用goctl生成时会报错，有其他方案可以做到吗？

我们从设计上不让共用，保持单一职责原则。
