### ISSUE TITLE
go-zero框架的golang版本近期有升级到1.6或1.7的计划吗?

### ISSUE THREAD

**Issue by chenquan** [tal-tech/go-zero#922]
如题
@kevwan

**Comment by kevwan** [comment]
支持的呀，不能直接限制到1.6或1.7，不然有些用户就用不了了

**Comment by chenquan** [comment]
> 支持的呀，不能直接限制到1.6或1.7，不然有些用户就用不了了
> 
> 你在微信群里嘛？

在微信群里的,万大佬. 因为想在go-zerok框架中加入`Embed`功能,所以希望有升级

**Comment by kevwan** [comment]
> > 支持的呀，不能直接限制到1.6或1.7，不然有些用户就用不了了
> > 你在微信群里嘛？
> 
> 在微信群里的,万大佬. 因为想在go-zerok框架中加入`Embed`功能,所以希望有升级

理解，但是怕升级就有一批用户不能用了，所以还是等泛型一起吧

**Comment by chenquan** [comment]
> > > 支持的呀，不能直接限制到1.6或1.7，不然有些用户就用不了了
> > > 你在微信群里嘛？
> > 
> > 
> > 在微信群里的,万大佬. 因为想在go-zerok框架中加入`Embed`功能,所以希望有升级
> 
> 理解，但是怕升级就有一批用户不能用了，所以还是等泛型一起吧

那提供提前预告一下嘛, 告诉大家预计会在golang1.8升级golang的版本

**Comment by kevwan** [comment]
> > > > 支持的呀，不能直接限制到1.6或1.7，不然有些用户就用不了了
> 
> > > > 你在微信群里嘛？
> 
> > > 
> 
> > > 
> 
> > > 在微信群里的,万大佬. 因为想在go-zerok框架中加入`Embed`功能,所以希望有升级
> 
> > 
> 
> > 理解，但是怕升级就有一批用户不能用了，所以还是等泛型一起吧
> 
> 
> 
> 那可以提前预告一下嘛, 告诉大家预计会在golang1.8升级golang的版本

之前群里讲过，泛型出来后我第一时间跟进
