### ISSUE TITLE
使用datasource方式生成mode失败，原因是生成的表名多了一对引号

### ISSUE THREAD

**Issue by zjp1531236645** [tal-tech/go-zero#923]
生成的代码
![bug](https://user-images.githubusercontent.com/25681526/129830206-bdc36ef3-a054-4536-b247-6857bd23d8c4.png)

目前我使用的解决方法 修改 new.go 16行
![bug1](https://user-images.githubusercontent.com/25681526/129830183-57e12bfd-9e9a-4c1f-b865-231bfd3a0a02.png)

**Comment by anqiansong** [comment]
这个需要执行 `goctl template clean` 清理一下模板
