### ISSUE TITLE
可以不使用缓存吗？

### ISSUE THREAD

**Issue by jesse996** [tal-tech/go-zero#927]
依赖注入的地方， model.NewPicModel() ，里面必须要填缓存，可以不使用缓存吗？

**Comment by anqiansong** [comment]
你生成model代码时不指定 `-c` flag就不会生成带缓存的代码了

**Comment by jesse996** [comment]
> 你生成model代码时不指定 `-c` flag就不会生成带缓存的代码了

好的谢谢
