### ISSUE TITLE
goctl如何生成 iOS 端 api 代码？

### ISSUE THREAD

**Issue by cyberity** [tal-tech/go-zero#930]
简介中提到：“go-zero 包含极简的 API 定义和生成工具 goctl，可以根据定义的 api 文件一键生成 Go, iOS, Android, Kotlin, Dart, TypeScript, JavaScript 代码，并可直接运行。” 但是没找到有 goctl 生成 iOS 代码的例子，也没有找到相关代码逻辑，求指点

**Comment by kevwan** [comment]
生成Java代码，然后用j2objc转换为iOS代码，我们是这么用的。

**Comment by wuyazi** [comment]
有考虑直接生成 swift 代码吗？
